% synthetic attributed product; regeneration recipe: .agent/memory.md (M4.7 queries suite).
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document(doc,ace_sha256(f2cbd2e45cf351ebdc1c338853a7d245488c07c9153399f9bfccfe476b65d5df),ulex(none)).
% S1: Synthetic attributed fixture sentence.
guideline_entity(actual,'$guideline_id'(product,doc,1,ref(1),[]),patient,countable) :- \+ guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),target,burn,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),target,burn,countable) :- guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),_L,left,countable), guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),_R,right,countable), guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),missing,absent,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l0,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l1,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l2,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l3,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l4,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l5,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l6,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l7,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l8,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l9,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l10,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l11,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l12,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l13,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l14,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l15,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l16,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l17,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l18,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l19,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l20,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l21,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l22,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l23,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l24,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l25,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l26,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l27,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l28,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l29,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l30,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l31,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l32,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l33,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l34,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l35,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l36,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l37,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l38,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l39,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l40,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l41,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l42,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l43,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l44,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l45,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l46,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l47,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l48,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l49,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l50,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l51,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l52,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l53,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l54,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l55,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l56,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l57,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l58,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l59,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l60,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l61,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l62,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l63,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l64,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l65,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l66,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l67,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l68,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l69,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l70,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l71,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l72,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l73,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l74,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l75,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l76,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l77,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l78,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l79,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l80,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l81,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l82,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l83,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l84,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l85,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l86,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l87,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l88,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l89,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l90,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l91,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l92,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l93,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l94,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l95,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l96,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l97,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l98,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l99,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l100,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l101,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l102,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l103,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l104,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l105,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l106,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l107,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l108,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l109,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l110,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l111,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l112,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l113,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l114,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l115,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l116,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l117,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l118,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l119,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l120,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l121,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l122,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l123,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l124,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l125,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l126,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l127,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l128,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l129,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l130,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l131,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l132,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l133,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l134,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l135,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l136,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l137,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l138,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l139,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l140,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l141,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l142,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l143,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l144,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l145,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l146,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l147,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l148,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l149,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l150,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l151,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l152,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l153,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l154,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l155,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l156,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l157,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l158,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l159,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l160,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l161,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l162,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l163,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l164,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l165,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l166,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l167,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l168,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l169,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l170,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l171,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l172,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l173,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l174,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l175,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l176,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l177,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l178,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l179,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l180,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l181,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l182,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l183,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l184,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l185,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l186,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l187,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l188,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l189,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l190,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l191,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l192,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l193,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l194,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l195,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l196,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l197,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l198,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l199,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l200,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l201,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l202,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l203,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l204,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l205,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l206,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l207,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l208,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l209,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l210,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l211,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l212,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l213,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l214,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l215,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l216,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l217,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l218,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l219,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l220,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l221,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l222,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l223,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l224,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l225,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l226,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l227,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l228,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l229,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l230,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l231,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l232,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l233,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l234,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l235,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l236,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l237,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l238,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l239,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l240,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l241,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l242,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l243,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l244,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l245,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l246,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l247,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l248,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l249,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l250,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l251,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l252,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l253,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l254,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l255,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l256,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l257,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l258,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l259,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l260,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l261,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l262,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l263,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l264,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l265,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l266,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l267,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l268,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l269,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l270,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l271,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l272,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l273,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l274,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l275,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l276,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l277,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l278,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l279,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l280,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l281,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l282,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l283,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l284,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l285,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l286,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l287,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l288,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l289,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l290,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l291,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l292,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l293,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l294,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l295,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l296,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l297,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l298,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l299,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l300,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l301,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l302,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l303,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l304,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l305,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l306,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l307,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l308,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l309,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l310,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l311,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l312,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l313,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l314,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l315,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l316,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l317,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l318,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l319,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l320,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l321,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l322,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l323,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l324,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l325,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l326,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l327,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l328,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l329,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l330,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l331,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l332,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l333,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l334,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l335,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l336,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l337,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l338,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l339,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l340,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l341,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l342,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l343,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l344,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l345,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l346,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l347,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l348,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l349,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l350,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l351,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l352,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l353,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l354,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l355,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l356,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l357,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l358,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l359,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l360,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l361,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l362,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l363,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l364,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l365,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l366,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l367,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l368,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l369,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l370,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l371,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l372,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l373,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l374,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l375,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l376,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l377,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l378,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l379,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l380,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l381,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l382,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l383,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l384,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l385,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l386,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l387,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l388,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l389,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l390,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l391,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l392,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l393,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l394,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l395,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l396,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l397,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l398,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),l399,left,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r0,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r1,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r2,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r3,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r4,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r5,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r6,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r7,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r8,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r9,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r10,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r11,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r12,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r13,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r14,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r15,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r16,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r17,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r18,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r19,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r20,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r21,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r22,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r23,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r24,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r25,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r26,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r27,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r28,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r29,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r30,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r31,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r32,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r33,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r34,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r35,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r36,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r37,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r38,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r39,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r40,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r41,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r42,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r43,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r44,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r45,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r46,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r47,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r48,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r49,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r50,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r51,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r52,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r53,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r54,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r55,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r56,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r57,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r58,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r59,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r60,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r61,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r62,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r63,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r64,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r65,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r66,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r67,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r68,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r69,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r70,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r71,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r72,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r73,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r74,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r75,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r76,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r77,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r78,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r79,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r80,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r81,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r82,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r83,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r84,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r85,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r86,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r87,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r88,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r89,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r90,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r91,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r92,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r93,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r94,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r95,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r96,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r97,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r98,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r99,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r100,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r101,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r102,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r103,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r104,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r105,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r106,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r107,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r108,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r109,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r110,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r111,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r112,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r113,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r114,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r115,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r116,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r117,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r118,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r119,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r120,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r121,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r122,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r123,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r124,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r125,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r126,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r127,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r128,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r129,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r130,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r131,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r132,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r133,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r134,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r135,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r136,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r137,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r138,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r139,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r140,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r141,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r142,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r143,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r144,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r145,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r146,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r147,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r148,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r149,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r150,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r151,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r152,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r153,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r154,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r155,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r156,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r157,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r158,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r159,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r160,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r161,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r162,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r163,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r164,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r165,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r166,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r167,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r168,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r169,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r170,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r171,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r172,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r173,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r174,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r175,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r176,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r177,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r178,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r179,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r180,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r181,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r182,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r183,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r184,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r185,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r186,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r187,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r188,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r189,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r190,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r191,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r192,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r193,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r194,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r195,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r196,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r197,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r198,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r199,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r200,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r201,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r202,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r203,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r204,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r205,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r206,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r207,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r208,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r209,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r210,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r211,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r212,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r213,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r214,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r215,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r216,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r217,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r218,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r219,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r220,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r221,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r222,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r223,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r224,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r225,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r226,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r227,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r228,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r229,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r230,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r231,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r232,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r233,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r234,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r235,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r236,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r237,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r238,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r239,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r240,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r241,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r242,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r243,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r244,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r245,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r246,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r247,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r248,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r249,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r250,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r251,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r252,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r253,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r254,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r255,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r256,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r257,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r258,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r259,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r260,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r261,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r262,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r263,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r264,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r265,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r266,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r267,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r268,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r269,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r270,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r271,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r272,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r273,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r274,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r275,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r276,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r277,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r278,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r279,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r280,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r281,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r282,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r283,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r284,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r285,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r286,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r287,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r288,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r289,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r290,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r291,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r292,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r293,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r294,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r295,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r296,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r297,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r298,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r299,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r300,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r301,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r302,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r303,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r304,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r305,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r306,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r307,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r308,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r309,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r310,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r311,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r312,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r313,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r314,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r315,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r316,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r317,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r318,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r319,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r320,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r321,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r322,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r323,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r324,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r325,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r326,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r327,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r328,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r329,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r330,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r331,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r332,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r333,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r334,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r335,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r336,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r337,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r338,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r339,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r340,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r341,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r342,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r343,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r344,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r345,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r346,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r347,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r348,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r349,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r350,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r351,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r352,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r353,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r354,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r355,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r356,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r357,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r358,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r359,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r360,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r361,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r362,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r363,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r364,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r365,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r366,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r367,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r368,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r369,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r370,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r371,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r372,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r373,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r374,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r375,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r376,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r377,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r378,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r379,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r380,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r381,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r382,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r383,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r384,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r385,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r386,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r387,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r388,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r389,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r390,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r391,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r392,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r393,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r394,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r395,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r396,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r397,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r398,right,countable).
guideline_entity('$guideline_id'(product,doc,1,ref(1),[]),r399,right,countable).
guideline_cardinality(actual,'$guideline_id'(product,doc,1,ref(1),[]),na,eq,1).
guideline_event(actual,'$guideline_id'(product,doc,1,ref(2),[]),wait).
guideline_arg(actual,'$guideline_id'(product,doc,1,ref(2),[]),1,'$guideline_id'(product,doc,1,ref(1),[])).
