cnl_guideline_mapping(1).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec01',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec01.ace'),ace_sha256('25f4bc0b5109717d108c138377be615898d95b4306ea1a0fc582dda009b47b35')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec01.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec02',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec02.ace'),ace_sha256('06212d79c2a865211f33f170fdbe7d5f5554701c83a116da02fb07531b0aa790')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec02.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec03',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec03.ace'),ace_sha256('65bafa8f9ffab76dd476a936f9b124e6baf210182ed1e23b4314ea3268db2e7f')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec03.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec04',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec04.ace'),ace_sha256('1a151ce7d02368aab8e51c8744194f5567199863872d64469891783ae242ead4')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec04.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec05',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec05.ace'),ace_sha256('65b66ef8b6cf5af09e9c0054f325c7cddda88ffaf563b2c5e6d1e1e659ec72c8')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec05.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec06',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec06.ace'),ace_sha256('4f45424d645b948f4e32145ed673c2718c58129c0325962658bab91b1d7291dd')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec06.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec07',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec07.ace'),ace_sha256('703b611339c19a38f1eede135c1c9f799f4cdbd81b36d676e614dd8ca42b89d2')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec07.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec08',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec08.ace'),ace_sha256('03f8f2ea32e635777708e8e0ada2c8726f8b01a134a7a5c55a1e6bfcf76025fd')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec08.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec09',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec09.ace'),ace_sha256('5d617e7fa8ce7cff0081b4814fc261212810447908e77ebb6089c8e7a37c07a0')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec09.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec10',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec10.ace'),ace_sha256(d28d0c2f2a893dc418d646e852d8dd4a0ebbeadcc8577ea970153af95ecf0c7a)),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec10.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec11',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec11.ace'),ace_sha256('82f481566c93cebc9a5612e09a417531cd0283da485fcfcd82043a9573ddb32c')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec11.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_document('cdc-2022-opioid','cdc2022-opioid-rec12',ace(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec12.ace'),ace_sha256('0e8bc74eac108b480eddf0a7510697523afee483f24ca8921ebdfafd9e03a6f5')),ulex(relpath('guidelines/cdc-2022-opioid/ace/cdc2022-opioid-rec12.ulex'),ulex_sha256('7926023c0fffd5d10d6e87f7d250ae2232508730e5a50cdbdef79bb29aa7613b'))).
mapping_region('cdc-2022-opioid','box3.grp.01').
mapping_region('cdc-2022-opioid','box3.grp.02').
mapping_region('cdc-2022-opioid','box3.grp.03').
mapping_region('cdc-2022-opioid','box3.grp.04').
mapping_region('cdc-2022-opioid','box3.rec.01').
mapping_region('cdc-2022-opioid','box3.rec.02').
mapping_region('cdc-2022-opioid','box3.rec.03').
mapping_region('cdc-2022-opioid','box3.rec.04').
mapping_region('cdc-2022-opioid','box3.rec.05').
mapping_region('cdc-2022-opioid','box3.rec.06').
mapping_region('cdc-2022-opioid','box3.rec.07').
mapping_region('cdc-2022-opioid','box3.rec.08').
mapping_region('cdc-2022-opioid','box3.rec.09').
mapping_region('cdc-2022-opioid','box3.rec.10').
mapping_region('cdc-2022-opioid','box3.rec.11').
mapping_region('cdc-2022-opioid','box3.rec.12').
mapping_claim('cdc-2022-opioid','box3.rec.01','claim.rec01.action-kind',projection(action_kind),docid('cdc2022-opioid-rec01'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('maximize-nonopioid-therapy',[named('Rec01-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.02','claim.rec02.action-kind',projection(action_kind),docid('cdc2022-opioid-rec02'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('maximize-nonopioid-therapy',[named('Rec02-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.03','claim.rec03.action-kind',projection(action_kind),docid('cdc2022-opioid-rec03'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('prescribe-immediate-release',[named('Rec03-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.04','claim.rec04.action-kind',projection(action_kind),docid('cdc2022-opioid-rec04'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('prescribe-lowest-effective-dosage',[named('Rec04-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.05','claim.rec05.applicability',projection(applicability),docid('cdc2022-opioid-rec05'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('avoid-abrupt-discontinuation',[named('Rec05-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.06','claim.rec06.action-kind',projection(action_kind),docid('cdc2022-opioid-rec06'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('limit-prescription-quantity',[named('Rec06-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.07','claim.rec07.action-kind',projection(action_kind),docid('cdc2022-opioid-rec07'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('reevaluate-benefits-and-risks',[named('Rec07-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.08','claim.rec08.action-kind',projection(action_kind),docid('cdc2022-opioid-rec08'),items([query_id(sentence(4),clause(1)),rule_id(sentence(3),clause(1))]),expected_answer(answer(query_id(sentence(4),clause(1)),wh(who),pred('offer-naloxone',[var(1)]),answers([pred('offer-naloxone',[named('Rec08-clinician')]),pred('offer-naloxone',[named('Rec08-peer')])])))).
mapping_claim('cdc-2022-opioid','box3.rec.09','claim.rec09.action-kind',projection(action_kind),docid('cdc2022-opioid-rec09'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('review-pdmp-data',[named('Rec09-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.10','claim.rec10.applicability',projection(applicability),docid('cdc2022-opioid-rec10'),items([query_id(sentence(4),clause(1)),rule_id(sentence(3),clause(1))]),expected_answer(answer(query_id(sentence(4),clause(1)),pred('consider-toxicology-testing',[named('Rec10-peer')]),not_proved))).
mapping_claim('cdc-2022-opioid','box3.rec.11','claim.rec11.action-kind',projection(action_kind),docid('cdc2022-opioid-rec11'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('use-particular-caution',[named('Rec11-clinician')]),proved))).
mapping_claim('cdc-2022-opioid','box3.rec.12','claim.rec12.action-kind',projection(action_kind),docid('cdc2022-opioid-rec12'),items([query_id(sentence(3),clause(1)),rule_id(sentence(2),clause(1))]),expected_answer(answer(query_id(sentence(3),clause(1)),pred('offer-medication-treatment',[named('Rec12-clinician')]),proved))).
mapping_residual('cdc-2022-opioid','box3.grp.01','residual.grp01.01',class(scope_deferred),detail(quote('Determining Whether or Not to Initiate Opioids for Pain (Recommendations 1 and 2)'),note('Needs grouping semantics that attach recommendations 1 and 2 to the initiate-opioids decision phase.'))).
mapping_residual('cdc-2022-opioid','box3.grp.02','residual.grp02.01',class(scope_deferred),detail(quote('Selecting Opioids and Determining Opioid Dosages (Recommendations 3, 4, and 5)'),note('Needs grouping semantics that attach recommendations 3 through 5 to the opioid-selection and dosage decision phase.'))).
mapping_residual('cdc-2022-opioid','box3.grp.03','residual.grp03.01',class(scope_deferred),detail(quote('Deciding Duration of Initial Opioid Prescription and Conducting Follow-Up (Recommendations 6 and 7)'),note('Needs grouping semantics that attach recommendations 6 and 7 to the prescription-duration and follow-up decision phase.'))).
mapping_residual('cdc-2022-opioid','box3.grp.04','residual.grp04.01',class(scope_deferred),detail(quote('Assessing Risk and Addressing Potential Harms of Opioid Use (Recommendations 8, 9, 10, 11, and 12)'),note('Needs grouping semantics that attach recommendations 8 through 12 to the risk-assessment and harm-mitigation decision phase.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.01',class(property),detail(quote('at least as effective as opioids'),note('Needs an effectiveness property with an explicit comparative degree.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.02',class(multi_entity),detail(quote('Nonopioid therapies are at least as effective as opioids'),note('Needs a comparative relation between nonopioid and opioid therapy entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.03',class(multi_entity),detail(quote('nonpharmacologic and nonopioid pharmacologic therapies'),note('Needs distinct therapy entities under one maximization action.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.04',class(scope_deferred),detail(quote('as appropriate for the specific condition and patient'),note('Needs condition-specific and patient-specific attachment for the suitability qualifier on the action.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.05',class(labeled_exception),detail(quote('only consider opioid therapy for acute pain if benefits are anticipated to outweigh risks to the patient'),note('Needs a labeled conditional exception governed by an anticipated benefit-risk comparison.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.06',class(transitive_relation),detail(quote('clinicians should discuss with patients the realistic benefits and known risks of opioid therapy'),note('Needs a clinician-patient discussion relation whose content names benefits and risks.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.07',class(direction_strength),detail(quote('recommendation category: B'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.08',class(certainty),detail(quote('evidence type: 3'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.09',class(population_threshold),detail(quote('for many common types of acute pain'),note('Needs a categorical condition-type threshold bounding the acute-pain effectiveness claim.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.10',class(temporal),detail(quote('Before prescribing opioid therapy for acute pain'),note('Needs a before-prescribing temporal-order constructor for the clinician-patient risk-benefit discussion.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.11',class(property),detail(quote('realistic benefits and known risks'),note('Needs a realism property on the discussed benefit entities distinct from the risk knowledge-status qualifier.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.12',class(certainty),detail(quote('anticipated to outweigh risks'),note('Needs an anticipation hedge on the benefit-risk comparison distinct from the labeled condition.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.13',class(copula_head),detail(quote('Nonopioid therapies are at least as effective as opioids'),note('Needs the source copular effectiveness-comparison head relation rather than only the action-kind projection.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.14',class(property),detail(quote('as appropriate'),note('Needs a suitability-manner qualifier on the therapy-maximization action distinct from its attachment scope.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.15',class(property),detail(quote('common types of acute pain'),note('Needs a commonness qualifier on the acute-pain condition types distinct from their population threshold.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.16',class(transitive_relation),detail(quote('consider opioid therapy'),note('Needs the consideration relation between clinician and opioid therapy beyond its conditional branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.17',class(multi_entity),detail(quote('benefits are anticipated to outweigh risks to the patient'),note('Needs an outweigh-comparison relation among benefit, risk, and patient entities distinct from its anticipation hedge.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.18',class(population_threshold),detail(quote('opioid therapy for acute pain'),note('Needs an acute-pain applicability condition scoping the consideration and discussion obligations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.19',class(transitive_relation),detail(quote('maximize use of nonpharmacologic and nonopioid pharmacologic therapies'),note('Needs the maximization relation between clinician and the therapy entities beyond their entity inventory.'))).
mapping_residual('cdc-2022-opioid','box3.rec.01','residual.rec01.20',class(certainty),detail(quote('known risks'),note('Needs a knowledge-status certainty qualifier on the discussed risk entities distinct from their realism property.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.01',class(copula_head),detail(quote('Nonopioid therapies are preferred for subacute and chronic pain'),note('Needs the source copular preference relation rather than only an action-kind projection.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.02',class(multi_entity),detail(quote('nonpharmacologic and nonopioid pharmacologic therapies'),note('Needs distinct nonopioid therapy entities under one maximization action.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.03',class(scope_deferred),detail(quote('as appropriate for the specific condition and patient'),note('Needs condition-specific and patient-specific attachment for the suitability qualifier on the action.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.04',class(labeled_exception),detail(quote('only consider initiating opioid therapy if expected benefits for pain and function are anticipated to outweigh risks to the patient'),note('Needs a labeled initiation condition with expected benefit-risk comparison.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.05',class(transitive_relation),detail(quote('clinicians should discuss with patients the realistic benefits and known risks of opioid therapy'),note('Needs a clinician-patient discussion relation whose content names benefits and risks.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.06',class(transitive_relation),detail(quote('should work with patients to establish treatment goals for pain and function'),note('Needs a clinician-patient goal-setting relation over pain and function goals.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.07',class(labeled_exception),detail(quote('should consider how opioid therapy will be discontinued if benefits do not outweigh risks'),note('Needs a conditional discontinuation-plan constructor tied to a negative benefit-risk result.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.08',class(direction_strength),detail(quote('recommendation category: A'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.09',class(certainty),detail(quote('evidence type: 2'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.10',class(temporal),detail(quote('Before starting opioid therapy for subacute or chronic pain'),note('Needs one before-starting temporal-order constructor shared by discussion, goal-setting, and discontinuation-planning obligations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.11',class(property),detail(quote('realistic benefits and known risks'),note('Needs a realism property on the discussed benefit entities distinct from the risk knowledge-status qualifier.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.12',class(disjunction),detail(quote('subacute or chronic pain'),note('Needs explicit alternatives for the two pain-duration applicability classes.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.13',class(certainty),detail(quote('anticipated to outweigh risks'),note('Needs an anticipation hedge on the benefit-risk comparison distinct from the labeled condition.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.14',class(certainty),detail(quote('expected benefits'),note('Needs an expectation hedge on the conditioned benefit entities distinct from the anticipation hedge on their comparison.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.15',class(property),detail(quote('as appropriate'),note('Needs a suitability-manner qualifier on the therapy-maximization action distinct from its attachment scope.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.16',class(transitive_relation),detail(quote('consider initiating opioid therapy'),note('Needs the initiation-consideration relation between clinician and opioid therapy beyond its conditional branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.17',class(multi_entity),detail(quote('expected benefits for pain and function are anticipated to outweigh risks to the patient'),note('Needs an outweigh-comparison relation among benefit, pain-function, risk, and patient entities distinct from its hedges.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.18',class(scope_deferred),detail(quote('to establish treatment goals for pain and function'),note('Needs purpose-clause attachment linking the goal-setting objective to the collaboration relation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.19',class(scope_deferred),detail(quote('how opioid therapy will be discontinued'),note('Needs embedded manner-interrogative attachment under the discontinuation-planning consideration.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.20',class(population_threshold),detail(quote('for subacute or chronic pain'),note('Needs a subacute-chronic applicability condition scoping the pre-initiation obligations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.21',class(property),detail(quote(preferred),note('Needs a preference-degree property on the copular head distinct from its profile wall.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.22',class(transitive_relation),detail(quote('consider how opioid therapy will be discontinued'),note('Needs the discontinuation-planning consideration relation between clinician and therapy distinct from its conditional branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.23',class(transitive_relation),detail(quote('maximize use of nonpharmacologic and nonopioid pharmacologic therapies'),note('Needs the maximization relation between clinician and the therapy entities beyond their entity inventory.'))).
mapping_residual('cdc-2022-opioid','box3.rec.02','residual.rec02.24',class(certainty),detail(quote('known risks'),note('Needs a knowledge-status certainty qualifier on the discussed risk entities distinct from their realism property.'))).
mapping_residual('cdc-2022-opioid','box3.rec.03','residual.rec03.01',class(disjunction),detail(quote('acute, subacute, or chronic pain'),note('Needs explicit alternatives for the three pain-duration applicability classes.'))).
mapping_residual('cdc-2022-opioid','box3.rec.03','residual.rec03.02',class(transitive_relation),detail(quote('clinicians should prescribe immediate-release opioids'),note('Needs the prescribing relation between clinician and opioid formulation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.03','residual.rec03.03',class(multi_entity),detail(quote('instead of extended-release and long-acting (ER/LA) opioids'),note('Needs a formulation-choice relation contrasting immediate-release with ER/LA entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.03','residual.rec03.04',class(direction_strength),detail(quote('recommendation category: A'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.03','residual.rec03.05',class(certainty),detail(quote('evidence type: 4'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.03','residual.rec03.06',class(temporal),detail(quote('When starting opioid therapy'),note('Needs a therapy-initiation phase condition scoping the formulation choice.'))).
mapping_residual('cdc-2022-opioid','box3.rec.03','residual.rec03.07',class(population_threshold),detail(quote('for acute, subacute, or chronic pain'),note('Needs a categorical pain-duration applicability condition scoping the formulation-choice obligation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.01',class(population_threshold),detail(quote('opioid-naïve patients'),note('Needs an explicit categorical population threshold for opioid-naïve status.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.02',class(disjunction),detail(quote('acute, subacute, or chronic pain'),note('Needs explicit alternatives for the three pain-duration applicability classes.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.03',class(dose_quantity),detail(quote('the lowest effective dosage'),note('Needs a dosage quantity constructor with minimum-threshold semantics.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.04',class(labeled_exception),detail(quote('If opioids are continued for subacute or chronic pain'),note('Needs a labeled continuation branch constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.05',class(property),detail(quote('use caution when prescribing opioids at any dosage'),note('Needs a caution qualifier attached to the prescribing action.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.06',class(multi_entity),detail(quote('carefully evaluate individual benefits and risks when considering increasing dosage'),note('Needs relations among individual benefits, risks, and a contemplated dosage increase.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.07',class(dose_quantity),detail(quote('avoid increasing dosage above levels likely to yield diminishing returns in benefits relative to risks to patients'),note('Needs a dosage-threshold constructor bound to diminishing-return evidence.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.08',class(direction_strength),detail(quote('recommendation category: A'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.09',class(certainty),detail(quote('evidence type: 3'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.10',class(temporal),detail(quote('When opioids are initiated'),note('Needs an initiation-phase condition scoping the lowest-effective-dosage obligation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.11',class(property),detail(quote('carefully evaluate'),note('Needs a care-manner qualifier on the benefit-risk evaluation distinct from its entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.12',class(certainty),detail(quote('likely to yield diminishing returns'),note('Needs a likelihood hedge on the diminishing-return threshold distinct from its dosage constructors.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.13',class(scope_deferred),detail(quote('at any dosage'),note('Needs universal dosage-range quantifier scope on the caution obligation distinct from its manner property.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.14',class(temporal),detail(quote('when considering increasing dosage'),note('Needs a consideration-event trigger scoping the benefit-risk evaluation obligation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.15',class(disjunction),detail(quote('subacute or chronic pain'),note('Needs explicit alternatives for the two pain-duration classes inside the continuation branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.16',class(property),detail(quote('individual benefits and risks'),note('Needs a patient-specific individuality qualifier on the evaluated benefit and risk entities distinct from their relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.17',class(temporal),detail(quote('when prescribing opioids'),note('Needs a prescribing-event trigger scoping the caution obligation distinct from its manner property.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.18',class(population_threshold),detail(quote('with acute, subacute, or chronic pain'),note('Needs a categorical pain-duration applicability condition on the initiation branch distinct from its opioid-naive-status threshold.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.19',class(population_threshold),detail(quote('for subacute or chronic pain'),note('Needs a categorical pain-duration applicability condition on the continuation branch distinct from its labeled constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.20',class(multi_entity),detail(quote('benefits relative to risks to patients'),note('Needs a relative benefit-risk comparison relation among benefit, risk, and patient entities distinct from its dosage threshold.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.21',class(transitive_relation),detail(quote('clinicians should prescribe the lowest effective dosage'),note('Needs the prescribing relation between clinician and dosage distinct from its quantity constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.22',class(transitive_relation),detail(quote('evaluate individual benefits and risks'),note('Needs the evaluation relation between clinician and the benefit and risk entities beyond their entity inventory.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.23',class(transitive_relation),detail(quote('should avoid increasing dosage'),note('Needs the avoidance relation between clinician and the dosage increase distinct from its threshold constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.24',class(property),detail(quote('effective dosage'),note('Needs an effectiveness property on the dosage entity distinct from its minimum threshold constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.04','residual.rec04.25',class(transitive_relation),detail(quote('yield diminishing returns in benefits'),note('Needs the yield relation between dosage levels and diminishing returns distinct from its threshold constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.01',class(multi_entity),detail(quote('clinicians should carefully weigh benefits and risks and exercise care when changing opioid dosage'),note('Needs weighing and care-exercise relations among clinician, benefit, risk, and dosage-change entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.02',class(labeled_exception),detail(quote('If benefits do not outweigh risks of continued opioid therapy'),note('Needs a labeled negative benefit-risk branch scoping the taper obligations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.03',class(disjunction),detail(quote('gradually taper to lower dosages or, if warranted based on the individual circumstances of the patient, appropriately taper and discontinue opioids'),note('Needs explicit taper-versus-discontinue alternatives.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.04',class(labeled_exception),detail(quote('Unless there are indications of a life-threatening issue such as warning signs of impending overdose (e.g., confusion, sedation, or slurred speech)'),note('Needs a labeled unless-branch constructor; the projection reads absence of an asserted warning as absence of indication.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.05',class(temporal),detail(quote('should not be discontinued abruptly, and clinicians should not rapidly reduce opioid dosages'),note('Needs abruptness and reduction-rate constraints.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.06',class(dose_quantity),detail(quote('opioid dosages from higher dosages'),note('Needs a dosage-level relation for reduction from higher dosages.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.07',class(direction_strength),detail(quote('recommendation category: B'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.08',class(certainty),detail(quote('evidence type: 4'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.09',class(transitive_relation),detail(quote('clinicians should optimize other therapies and work closely with patients'),note('Needs distinct clinician-other-therapy optimization and clinician-patient collaboration relations on the negative benefit-risk branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.10',class(population_threshold),detail(quote('For patients already receiving opioid therapy'),note('Needs a categorical already-receiving population condition scoping the whole recommendation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.11',class(property),detail(quote('carefully weigh benefits and risks and exercise care'),note('Needs care-manner qualifiers on weighing and dosage-change handling distinct from their entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.12',class(property),detail(quote('gradually taper'),note('Needs a gradual taper-manner qualifier distinct from the taper alternatives.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.13',class(temporal),detail(quote('while continuing opioid therapy'),note('Needs a concurrent-state constructor for optimization during continued therapy distinct from its entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.14',class(disjunction),detail(quote('confusion, sedation, or slurred speech'),note('Needs explicit alternatives for the warning-sign examples inside the labeled exception.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.15',class(labeled_exception),detail(quote('if warranted based on the individual circumstances of the patient'),note('Needs a nested warranted-condition on the discontinue alternative distinct from the taper disjunction.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.16',class(property),detail(quote('work closely with patients'),note('Needs a closeness-manner qualifier on the clinician-patient collaboration distinct from its entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.17',class(property),detail(quote('appropriately taper'),note('Needs an appropriateness taper-manner qualifier distinct from the taper alternatives.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.18',class(labeled_exception),detail(quote('If benefits outweigh risks of continued opioid therapy'),note('Needs a labeled positive benefit-risk branch scoping the continued-therapy obligations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.19',class(property),detail(quote('life-threatening issue'),note('Needs a life-threatening severity qualifier on the exception issue distinct from its labeled branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.20',class(temporal),detail(quote('impending overdose'),note('Needs an imminence qualifier on the threatened overdose event distinct from its labeled branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.21',class(temporal),detail(quote('when changing opioid dosage'),note('Needs a dosage-change-event trigger scoping the care obligation distinct from its entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.22',class(dose_quantity),detail(quote('taper to lower dosages'),note('Needs a lower-dosage target quantity constructor distinct from the taper alternatives.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.23',class(scope_deferred),detail(quote('such as warning signs of impending overdose'),note('Needs non-exhaustive exemplification attachment linking the warning-sign examples to the life-threatening-issue class.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.24',class(property),detail(quote('individual circumstances of the patient'),note('Needs a patient-specific individuality qualifier on the warranting circumstances distinct from their exception branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.25',class(scope_deferred),detail(quote('to optimize nonopioid therapies'),note('Needs purpose-clause attachment linking the optimization objective to the positive-branch collaboration.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.26',class(scope_deferred),detail(quote('to gradually taper'),note('Needs purpose-clause attachment linking the taper objective to the negative-branch collaboration.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.27',class(transitive_relation),detail(quote('indications of a life-threatening issue'),note('Needs the indication evidence relation between warning signs and the life-threatening issue distinct from its labeled branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.28',class(multi_entity),detail(quote('benefits outweigh risks of continued opioid therapy'),note('Needs an outweigh-comparison relation among benefit, risk, and continued-therapy entities distinct from its labeled branches.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.29',class(transitive_relation),detail(quote('work closely with patients to optimize nonopioid therapies'),note('Needs distinct clinician-patient collaboration and nonopioid-therapy optimization relations on the positive benefit-risk branch.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.30',class(transitive_relation),detail(quote('reduce opioid dosages'),note('Needs the reduction relation between clinician and dosages underlying the rate prohibition.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.31',class(scope_deferred),detail(quote('e.g., confusion, sedation, or slurred speech'),note('Needs non-exhaustive exemplification attachment linking the symptom examples to the warning-sign class distinct from their alternatives constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.32',class(transitive_relation),detail(quote('taper to lower dosages'),note('Needs the taper relation between clinician and dosages distinct from its alternatives constructor and target quantity.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.33',class(transitive_relation),detail(quote('taper and discontinue opioids'),note('Needs the discontinuation relation between clinician and opioids distinct from its alternatives constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.05','residual.rec05.34',class(temporal),detail(quote('gradually taper to lower dosages'),note('Needs the positive-pole reduction-rate constraint on the commanded taper distinct from its manner property and the prohibited abrupt-rapid pole.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.01',class(population_threshold),detail(quote('When opioids are needed for acute pain'),note('Needs a categorical opioid-need condition for the acute-pain applicability population.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.02',class(transitive_relation),detail(quote('clinicians should prescribe no greater quantity'),note('Needs the prescribing relation between clinician and an opioid quantity.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.03',class(dose_quantity),detail(quote('no greater quantity than needed'),note('Needs a bounded prescription-quantity constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.04',class(temporal),detail(quote('the expected duration of pain'),note('Needs a duration constructor tied to the prescription quantity.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.05',class(population_threshold),detail(quote('pain severe enough to require opioids'),note('Needs an explicit severity threshold for the applicable pain population.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.06',class(direction_strength),detail(quote('recommendation category: A'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.07',class(certainty),detail(quote('evidence type: 4'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.08',class(certainty),detail(quote('expected duration of pain'),note('Needs an expectation hedge on the pain-duration bound distinct from its duration constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.06','residual.rec06.09',class(transitive_relation),detail(quote('severe enough to require opioids'),note('Needs the requirement relation between pain severity and opioid need distinct from its population threshold.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.01',class(temporal),detail(quote('within 1–4 weeks of starting opioid therapy'),note('Needs an interval constructor anchored to therapy start.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.02',class(disjunction),detail(quote('subacute or chronic pain or of dosage escalation'),note('Needs explicit alternatives for pain duration and dosage-escalation triggers.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.03',class(transitive_relation),detail(quote('evaluate benefits and risks with patients'),note('Needs a clinician-patient evaluation relation over benefits and risks.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.04',class(temporal),detail(quote('regularly reevaluate'),note('Needs a recurring-frequency constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.05',class(scope_deferred),detail(quote('continued opioid therapy'),note('Needs continuation-state attachment for the recurring reevaluation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.06',class(direction_strength),detail(quote('recommendation category: A'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.07',class(certainty),detail(quote('evidence type: 4'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.08',class(temporal),detail(quote('dosage escalation'),note('Needs the interval constructor anchored to the dosage-escalation event distinct from the therapy-start anchor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.09',class(temporal),detail(quote('continued opioid therapy'),note('Needs an ongoing-continuation state constructor distinct from its attachment scope.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.10',class(population_threshold),detail(quote('for subacute or chronic pain'),note('Needs a categorical pain-duration applicability condition scoping the evaluation obligations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.07','residual.rec07.11',class(scope_deferred),detail(quote('starting opioid therapy for subacute or chronic pain'),note('Needs pain-duration attachment restricted to the therapy-start anchor distinct from the escalation anchor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.01',class(temporal),detail(quote('Before starting and periodically during continuation of opioid therapy'),note('Needs start-relative and periodic timing constructors.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.02',class(transitive_relation),detail(quote('evaluate risk for opioid-related harms and discuss risk with patients'),note('Needs evaluation and clinician-patient discussion relations over harm risk.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.03',class(multi_entity),detail(quote('work with patients to incorporate into the management plan strategies to mitigate risk'),note('Needs entity relations among management plan, mitigation strategies, and risk.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.04',class(scope_deferred),detail(quote('including offering naloxone'),note('Needs inclusion attachment showing naloxone as one member of a broader strategy set.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.05',class(transitive_relation),detail(quote('offering naloxone'),note('Needs the offer relation between clinician and naloxone beyond its action-kind label.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.06',class(direction_strength),detail(quote('recommendation category: A'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.07',class(certainty),detail(quote('evidence type: 4'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.08',class(property),detail(quote('opioid-related harms'),note('Needs an opioid-related qualifier on the harm entities distinct from their evaluation and discussion relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.09',class(scope_deferred),detail(quote('to incorporate into the management plan'),note('Needs purpose-clause attachment linking plan incorporation to the collaboration relation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.10',class(scope_deferred),detail(quote('strategies to mitigate risk'),note('Needs purpose-clause attachment linking risk mitigation to the strategy entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.11',class(scope_deferred),detail(quote('during continuation of opioid therapy'),note('Needs continuation-state attachment for the periodic evaluation branch distinct from its timing constructors.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.12',class(transitive_relation),detail(quote('should work with patients to incorporate'),note('Needs the clinician-patient collaboration relation underlying the plan-incorporation obligation beyond its entity inventory.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.13',class(transitive_relation),detail(quote('incorporate into the management plan'),note('Needs the incorporation relation between strategies and the management plan distinct from its purpose attachment.'))).
mapping_residual('cdc-2022-opioid','box3.rec.08','residual.rec08.14',class(transitive_relation),detail(quote('mitigate risk'),note('Needs the mitigation relation between strategies and risk distinct from its purpose attachment.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.01',class(temporal),detail(quote('When prescribing initial opioid therapy for acute, subacute, or chronic pain, and periodically during opioid therapy for chronic pain'),note('Needs distinct initial and periodic review timing constructors.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.02',class(disjunction),detail(quote('acute, subacute, or chronic pain'),note('Needs explicit alternatives for the three pain-duration applicability classes.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.03',class(transitive_relation),detail(quote('review the patient’s history of controlled substance prescriptions using state prescription drug monitoring program (PDMP) data'),note('Needs clinician-history review and PDMP-data-use relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.04',class(scope_deferred),detail(quote('to determine whether the patient is receiving'),note('Needs purpose-clause attachment for the PDMP review.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.05',class(dose_quantity),detail(quote('opioid dosages'),note('Needs an opioid dosage quantity constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.06',class(population_threshold),detail(quote('dosages or combinations that put the patient at high risk for overdose'),note('Needs a categorical high-risk threshold bound to dosage or combination evidence.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.07',class(direction_strength),detail(quote('recommendation category: B'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.08',class(certainty),detail(quote('evidence type: 4'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.09',class(disjunction),detail(quote('dosages or combinations'),note('Needs an explicit dosage-versus-combination alternative constructor inside the categorical high-risk trigger.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.10',class(transitive_relation),detail(quote('determine whether the patient is receiving opioid dosages'),note('Needs the patient-receiving relation over dosages and combinations underlying the high-risk determination.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.11',class(scope_deferred),detail(quote('periodically during opioid therapy for chronic pain'),note('Needs chronic-pain attachment restricted to the periodic review branch distinct from its timing constructors.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.12',class(property),detail(quote('state prescription drug monitoring program'),note('Needs a jurisdictional qualifier on the PDMP data source distinct from its review and data-use relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.13',class(scope_deferred),detail(quote('initial opioid therapy for acute, subacute, or chronic pain'),note('Needs pain-duration attachment restricted to the initial prescribing branch distinct from its timing constructors.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.14',class(scope_deferred),detail(quote('whether the patient is receiving'),note('Needs embedded polar-proposition attachment under the determination relation distinct from its purpose clause.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.15',class(transitive_relation),detail(quote('put the patient at high risk for overdose'),note('Needs the risk-imposition relation from dosage and combination evidence to overdose risk distinct from its categorical threshold.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.16',class(population_threshold),detail(quote('for acute, subacute, or chronic pain'),note('Needs a categorical pain-duration applicability condition scoping the initial review obligation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.09','residual.rec09.17',class(population_threshold),detail(quote('opioid therapy for chronic pain'),note('Needs a categorical chronic-pain applicability condition scoping the periodic review obligation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.01',class(disjunction),detail(quote('subacute or chronic pain'),note('Needs explicit alternatives for the two pain-duration applicability classes.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.02',class(multi_entity),detail(quote('benefits and risks of toxicology testing'),note('Needs a relation between testing benefits and risks.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.03',class(transitive_relation),detail(quote('to assess for prescribed medications'),note('Needs an assessment relation from testing to medication evidence.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.04',class(multi_entity),detail(quote('prescribed medications as well as other prescribed and nonprescribed controlled substances'),note('Needs distinct medication and controlled-substance entities under the assessment relation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.05',class(direction_strength),detail(quote('recommendation category: B'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.06',class(certainty),detail(quote('evidence type: 4'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.07',class(property),detail(quote('prescribed and nonprescribed'),note('Needs prescription-status qualifying properties on controlled-substance entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.08',class(temporal),detail(quote('When prescribing opioids'),note('Needs a prescribing-phase condition scoping the toxicology-testing consideration.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.09',class(property),detail(quote('prescribed medications'),note('Needs a prescription-status qualifier on the medication entities distinct from the controlled-substance contrast.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.10',class(transitive_relation),detail(quote('consider the benefits and risks of toxicology testing'),note('Needs the clinician consideration relation over testing benefits and risks beyond its entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.10','residual.rec10.11',class(scope_deferred),detail(quote('toxicology testing to assess'),note('Needs purpose-clause attachment linking the assessment objective to the toxicology testing.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.01',class(property),detail(quote('particular caution'),note('Needs a degree-bearing caution property rather than only an action-kind atom.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.02',class(multi_entity),detail(quote('opioid pain medication and benzodiazepines concurrently'),note('Needs a concurrent relation between opioid medication and benzodiazepine entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.03',class(temporal),detail(quote(concurrently),note('Needs a concurrency constructor for simultaneous prescribing.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.04',class(multi_entity),detail(quote('benefits outweigh risks of concurrent prescribing of opioids and other central nervous system depressants'),note('Needs benefit-risk comparison over opioids and other CNS depressant entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.05',class(transitive_relation),detail(quote('consider whether benefits outweigh risks'),note('Needs an explicit consideration relation over the benefit-risk proposition.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.06',class(direction_strength),detail(quote('recommendation category: B'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.07',class(certainty),detail(quote('evidence type: 3'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.08',class(temporal),detail(quote('when prescribing opioid pain medication and benzodiazepines concurrently'),note('Needs a prescribing-event trigger for the caution obligation distinct from the concurrency constructor.'))).
mapping_residual('cdc-2022-opioid','box3.rec.11','residual.rec11.09',class(scope_deferred),detail(quote('whether benefits outweigh risks'),note('Needs embedded polar-proposition attachment under the consideration relation distinct from its entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.01',class(disjunction),detail(quote('offer or arrange treatment'),note('Needs explicit alternatives for offering versus arranging treatment.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.02',class(property),detail(quote('evidence-based medications'),note('Needs an evidence-based qualification on medication entities.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.03',class(transitive_relation),detail(quote('treatment with evidence-based medications to treat patients with opioid use disorder'),note('Needs relations among treatment, medications, patients, and opioid use disorder.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.04',class(labeled_exception),detail(quote('Detoxification on its own, without medications for opioid use disorder'),note('Needs an explicit without-medication exception on detoxification.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.05',class(copula_head),detail(quote('is not recommended for opioid use disorder'),note('Needs the negative copular recommendation head.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.06',class(multi_entity),detail(quote('because of increased risks for resuming drug use, overdose, and overdose death'),note('Needs distinct adverse-outcome entities under the detoxification nonrecommendation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.07',class(direction_strength),detail(quote('recommendation category: A'),note('Needs an explicit constructor for recommendation category and direction strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.08',class(certainty),detail(quote('evidence type: 1'),note('Needs an explicit constructor for evidence type and certainty.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.09',class(property),detail(quote('increased risks'),note('Needs an increased-degree qualifier on the adverse-outcome risks distinct from their entity relations.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.10',class(population_threshold),detail(quote('patients with opioid use disorder'),note('Needs a categorical opioid-use-disorder population condition for the treatment applicability.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.11',class(scope_deferred),detail(quote('because of increased risks'),note('Needs causal-grounding attachment linking the adverse-outcome risks to the nonrecommendation.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.12',class(scope_deferred),detail(quote('to treat patients with opioid use disorder'),note('Needs purpose-clause attachment linking the treatment objective to the evidence-based medications.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.13',class(direction_strength),detail(quote('not recommended for opioid use disorder'),note('Needs a negative recommendation-direction constructor distinct from the copular head and the category strength.'))).
mapping_residual('cdc-2022-opioid','box3.rec.12','residual.rec12.14',class(transitive_relation),detail(quote('arrange treatment'),note('Needs the arrangement relation between clinician and treatment on the unprojected alternative branch.'))).
