% cdc2022-opioid-rec04.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec04',ace_sha256('7551395b901785b7b0bf7b1295ae6003748ff2af4cadf0bf057d6222582a6ec5'),ulex(sha256(bac3441c3cba94d1d496ba3b04390eae38a0826cd30a0a0f713112b2172476ce))).
% S1: A recommendation is a category-A-recommendation and is an evidence-type-3-recommendation.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(1),[]),recommendation,countable).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(1),[]),na,eq,1).
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(2),[]),'category-A-recommendation',countable).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(2),[]),na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(3),[]),be).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(3),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(1),[])).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(3),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(2),[])).
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(4),[]),'evidence-type-3-recommendation',countable).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(4),[]),na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(5),[]),be).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(5),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(1),[])).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(5),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',1,ref(4),[])).
% S2: If a clinician starts an opioid-therapy for an opioid-naive-patient that has an acute-pain then the clinician should prescribe a lowest-effective-dosage.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',2,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',2,ref(7),[A,B,C,D,E,F]),'lowest-effective-dosage',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',2,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',2,ref(8),[A,B,C,D,E,F]),prescribe) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',2,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',2,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',2,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
% S3: If a clinician starts an opioid-therapy for an opioid-naive-patient that has a subacute-pain then the clinician should prescribe a lowest-effective-dosage.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',3,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'subacute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',3,ref(7),[A,B,C,D,E,F]),'lowest-effective-dosage',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'subacute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',3,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'subacute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',3,ref(8),[A,B,C,D,E,F]),prescribe) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'subacute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',3,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'subacute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',3,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',3,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'subacute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
% S4: If a clinician starts an opioid-therapy for an opioid-naive-patient that has a chronic-pain then the clinician should prescribe a lowest-effective-dosage.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',4,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'chronic-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',4,ref(7),[A,B,C,D,E,F]),'lowest-effective-dosage',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'chronic-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',4,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'chronic-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',4,ref(8),[A,B,C,D,E,F]),prescribe) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'chronic-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',4,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'chronic-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',4,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',4,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'opioid-naive-patient',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,'chronic-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,C), guideline_arg(actual,E,2,D), guideline_event(actual,F,start), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_pp(actual,F,for,C).
% S5: If a clinician continues an opioid-therapy for a subacute-pain and the clinician prescribes an opioid at a dosage then the clinician should heed a caution.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',5,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',5,ref(8),[A,B,C,D,E,F,G]),caution,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',5,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',5,ref(9),[A,B,C,D,E,F,G]),heed) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',5,ref(9),[A,B,C,D,E,F,G]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',5,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',5,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
% S6: If a clinician continues an opioid-therapy for a chronic-pain and the clinician prescribes an opioid at a dosage then the clinician should heed a caution.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',6,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',6,ref(8),[A,B,C,D,E,F,G]),caution,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',6,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',6,ref(9),[A,B,C,D,E,F,G]),heed) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',6,ref(9),[A,B,C,D,E,F,G]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec04',6,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',6,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,opioid,countable), guideline_cardinality(actual,E,na,eq,1), guideline_entity(actual,F,dosage,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,prescribe), guideline_arg(actual,G,1,A), guideline_arg(actual,G,2,E), guideline_pp(actual,G,at,F).
% S7: If a clinician continues an opioid-therapy for a subacute-pain and the clinician considers a dosage-increase then the clinician should evaluate an individual-benefit and should evaluate an individual-risk.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',7,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(7),[A,B,C,D,E,F]),'individual-benefit',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(8),[A,B,C,D,E,F]),evaluate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',7,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(9),[A,B,C,D,E,F]),'individual-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(10),[A,B,C,D,E,F]),evaluate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(10),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',7,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',7,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
% S8: If a clinician continues an opioid-therapy for a chronic-pain and the clinician considers a dosage-increase then the clinician should evaluate an individual-benefit and should evaluate an individual-risk.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',8,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(7),[A,B,C,D,E,F]),'individual-benefit',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(8),[A,B,C,D,E,F]),evaluate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',8,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(9),[A,B,C,D,E,F]),'individual-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(10),[A,B,C,D,E,F]),evaluate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(10),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',8,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',8,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'dosage-increase',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,E).
% S9: If a clinician continues an opioid-therapy for a subacute-pain then the clinician should avoid an increase above a diminishing-return-level.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(5),[A,B,C,D]),increase,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(6),[A,B,C,D]),'diminishing-return-level',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(7),[A,B,C,D]),avoid) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(7),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(7),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec04',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(7),[A,B,C,D]),above,'$guideline_id'(product,'cdc2022-opioid-rec04',9,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'subacute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
% S10: If a clinician continues an opioid-therapy for a chronic-pain then the clinician should avoid an increase above a diminishing-return-level.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(5),[A,B,C,D]),increase,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(6),[A,B,C,D]),'diminishing-return-level',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(7),[A,B,C,D]),avoid) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(7),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(7),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec04',10,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(7),[A,B,C,D]),above,'$guideline_id'(product,'cdc2022-opioid-rec04',10,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'chronic-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,continue), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
