% cdc2022-opioid-s46-16.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s46-16',ace_sha256(ebdded13339d8d586a9501754f05b4522cfc07df5d7fad832ebabbb0d63e9e2f),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a clinician prescribes an opioid to a patient and the patient has a mild-sleep-disordered-breathing then the clinician should use a careful-monitoring for the patient and should use a cautious-dose-titration for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(7),[A,B,C,D,E,F]),'careful-monitoring',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(8),[A,B,C,D,E,F]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(8),[A,B,C,D,E,F]),for,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(9),[A,B,C,D,E,F]),'cautious-dose-titration',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(10),[A,B,C,D,E,F]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(10),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s46-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s46-16',1,ref(10),[A,B,C,D,E,F]),for,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,prescribe), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,to,C), guideline_entity(actual,E,'mild-sleep-disordered-breathing',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
