% cdc2022-opioid-rec12-imp09.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec12-imp09',ace_sha256('99b48bd64c5611bb95615e5753ff0d0eb287d2db1b40760726c512b18b7b726a'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a clinician prescribes an opioid then the clinician should identify an opioid-use-disorder-treatment-resource in a community.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(4),[A,B,C]),'opioid-use-disorder-treatment-resource',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(5),[A,B,C]),community,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(5),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(6),[A,B,C]),identify) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(6),[A,B,C]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(6),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(4),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',1,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(6),[A,B,C]),in,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',1,ref(5),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S2: If a clinician prescribes an opioid then the clinician should establish an opioid-use-disorder-referral-network in a community.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(4),[A,B,C]),'opioid-use-disorder-referral-network',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(5),[A,B,C]),community,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(5),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(6),[A,B,C]),establish) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(6),[A,B,C]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(6),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(4),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',2,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(6),[A,B,C]),in,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',2,ref(5),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S3: Every opioid-use-disorder-referral-network should span a patient-needed-level-of-care.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec12-imp09',3,box(1),[A]),should) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',3,ref(2),[A]),'patient-needed-level-of-care',countable) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',3,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',3,ref(3),[A]),span) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',3,ref(3),[A]),1,A) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',3,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',3,ref(2),[A])) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
% S4: Every opioid-use-disorder-referral-network may enable a rapid-clinical-collaboration.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec12-imp09',4,box(1),[A]),may) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',4,ref(2),[A]),'rapid-clinical-collaboration',countable) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',4,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',4,ref(3),[A]),enable) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',4,ref(3),[A]),1,A) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',4,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',4,ref(2),[A])) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
% S5: Every opioid-use-disorder-referral-network may enable a rapid-patient-referral.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec12-imp09',5,box(1),[A]),may) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',5,ref(2),[A]),'rapid-patient-referral',countable) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',5,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',5,ref(3),[A]),enable) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',5,ref(3),[A]),1,A) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',5,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',5,ref(2),[A])) :- guideline_entity(actual,A,'opioid-use-disorder-referral-network',countable), guideline_cardinality(actual,A,na,eq,1).
% S6: If a clinician prescribes an opioid then the clinician should participate in an opioid-prescribing-clinician-collaboration.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec12-imp09',6,box(1),[A,B,C]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',6,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',6,ref(4),[A,B,C]),'opioid-prescribing-clinician-collaboration',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',6,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',6,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',6,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',6,ref(5),[A,B,C]),participate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',6,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',6,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',6,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',6,ref(5),[A,B,C]),in,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',6,ref(4),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,prescribe), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S7: Every opioid-prescribing-clinician-collaboration should ensure a sufficient-opioid-use-disorder-treatment-capacity at a clinical-practice-organization.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),should) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(2),[A]),'sufficient-opioid-use-disorder-treatment-capacity',countable) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(3),[A]),'clinical-practice-organization',countable) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(4),[A]),ensure) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(4),[A]),1,A) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(2),[A])) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec12-imp09',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(4),[A]),at,'$guideline_id'(product,'cdc2022-opioid-rec12-imp09',7,ref(3),[A])) :- guideline_entity(actual,A,'opioid-prescribing-clinician-collaboration',countable), guideline_cardinality(actual,A,na,eq,1).
