% cdc2022-opioid-rec02-imp09.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec02-imp09',ace_sha256('2ac0b29c5e2996f6c45b813e6ec84ce8c2901a6e2092028bf3bd12badd9e7afc'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a patient has a chronic-low-back-pain and a nonpharmacologic-approach does not improve the chronic-low-back-pain and the patient does not have a contraindication then every clinician can consider an NSAID and can consider a duloxetine.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(3),[A,B,C,D,E]),can) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(9),[A,B,C,D,E]),'NSAID',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(9),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(10),[A,B,C,D,E]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(10),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(10),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(9),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(4),[A,B,C,D,E]),can) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(11),[A,B,C,D,E]),duloxetine,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(11),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(12),[A,B,C,D,E]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(12),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp09',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(12),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp09',1,ref(11),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'chronic-low-back-pain',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'nonpharmacologic-approach',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,F,-), guideline_event(F,G,improve), guideline_arg(F,G,1,D), guideline_arg(F,G,2,B), guideline_operator(actual,H,-), guideline_entity(H,I,contraindication,countable), guideline_cardinality(H,I,na,eq,1), guideline_event(H,J,have), guideline_arg(H,J,1,A), guideline_arg(H,J,2,I), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
