% cdc2022-opioid-rec06-imp15.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec06-imp15',ace_sha256('5c6393c7aebefc49341b3ffbf1309505ac657130e616bcd825b043a126efa6c8'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a patient has a taper-plan and the patient has a hospital-discharge and a care-coordinating-clinician coordinates an outpatient-care for the patient then every clinician should discuss the taper-plan with the patient before the hospital-discharge and should discuss the taper-plan with the care-coordinating-clinician before the hospital-discharge.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(1),[A,B,C,D,E,F,G,H,I]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(10),[A,B,C,D,E,F,G,H,I]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(10),[A,B,C,D,E,F,G,H,I]),1,I) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(10),[A,B,C,D,E,F,G,H,I]),2,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(10),[A,B,C,D,E,F,G,H,I]),before,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(10),[A,B,C,D,E,F,G,H,I]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(2),[A,B,C,D,E,F,G,H,I]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(2),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(11),[A,B,C,D,E,F,G,H,I]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(2),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(11),[A,B,C,D,E,F,G,H,I]),1,I) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(2),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(11),[A,B,C,D,E,F,G,H,I]),2,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(2),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(11),[A,B,C,D,E,F,G,H,I]),before,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec06-imp15',1,box(2),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp15',1,ref(11),[A,B,C,D,E,F,G,H,I]),with,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-plan',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'hospital-discharge',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'care-coordinating-clinician',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'outpatient-care',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,coordinate), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_pp(actual,H,for,A), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
