% cdc2022-opioid-rec02.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec02',ace_sha256(cbb3c4e8db7fb033fcc00bc6f967eff4b77a501d311ae323074f5bb77f1e57cb),ulex(sha256('06c1c26d6b6abe1436b8c94a276937ad072806062117417de2ab8086fdf9a3e9'))).
% S1: A recommendation is a category-A-recommendation and is an evidence-type-2-recommendation.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(1),[]),recommendation,countable).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(1),[]),na,eq,1).
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(2),[]),'category-A-recommendation',countable).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(2),[]),na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(3),[]),be).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(3),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(1),[])).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(3),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(2),[])).
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(4),[]),'evidence-type-2-recommendation',countable).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(4),[]),na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(5),[]),be).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(5),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(1),[])).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(5),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',1,ref(4),[])).
% S2: Every clinician should maximize a nonopioid-therapy for a subacute-pain and should maximize a nonopioid-therapy for a chronic-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(2),[A]),'nonopioid-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(3),[A]),'subacute-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(4),[A]),maximize) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(5),[A]),'nonopioid-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(5),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(6),[A]),'chronic-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(6),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(7),[A]),maximize) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(7),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(7),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(5),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',2,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(7),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02',2,ref(6),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S3: If an opioid-benefit does not outweigh an opioid-risk then every clinician should not consider an opioid-therapy.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',3,box(2),[A,B]),-) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_operator('$guideline_id'(context,'cdc2022-opioid-rec02',3,box(2),[A,B]),'$guideline_id'(context,'cdc2022-opioid-rec02',3,box(3),[A,B]),should) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',3,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',3,ref(5),[A,B]),'opioid-therapy',countable) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',3,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',3,ref(5),[A,B]),na,eq,1) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',3,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',3,ref(6),[A,B]),consider) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',3,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',3,ref(6),[A,B]),1,B) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',3,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',3,ref(6),[A,B]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',3,ref(5),[A,B])) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
% S4: Every clinician should discuss a realistic-benefit with a patient before an initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(2),[A]),'realistic-benefit',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(4),[A]),initiation,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(5),[A]),discuss) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02',4,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S5: Every clinician should discuss a known-risk with a patient before an initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(2),[A]),'known-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(4),[A]),initiation,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(5),[A]),discuss) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02',5,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S6: Every clinician should establish a pain-goal with a patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(2),[A]),'pain-goal',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(4),[A]),establish) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(4),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02',6,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S7: Every clinician should establish a function-goal with a patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(2),[A]),'function-goal',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(4),[A]),establish) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(4),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02',7,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S8: If an opioid-benefit does not outweigh an opioid-risk then every clinician should consider a discontinuation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02',8,box(2),[A,B]),should) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02',8,box(2),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',8,ref(5),[A,B]),discontinuation,countable) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02',8,box(2),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',8,ref(5),[A,B]),na,eq,1) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02',8,box(2),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',8,ref(6),[A,B]),consider) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',8,box(2),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',8,ref(6),[A,B]),1,B) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02',8,box(2),[A,B]),'$guideline_id'(product,'cdc2022-opioid-rec02',8,ref(6),[A,B]),2,'$guideline_id'(product,'cdc2022-opioid-rec02',8,ref(5),[A,B])) :- guideline_entity(actual,A,'opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'opioid-risk',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,outweigh), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
