% cdc2022-opioid-rec01-imp04.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec01-imp04',ace_sha256('35d0ac323bfada3b413b0d89203cc88a5ddc36c3914a4479b184fc184469eecb'),ulex(sha256('6bd0df91739d5a42b1a472d866e0dd72897517f8e4652458e4893adbed9cc663'))).
% S1: If a patient has a long-term-opioid-use and needs an additional-medication for an acute-pain and a nonopioid-medication is possible then every clinician should use the nonopioid-medication.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec01-imp04',1,box(1),[A,B,C,D,E,F,G,H,I,J]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-medication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,'nonopioid-medication',countable), guideline_cardinality(actual,G,na,eq,1), guideline_property(actual,H,possible,pos), guideline_event(actual,I,be), guideline_arg(actual,I,1,G), guideline_arg(actual,I,2,H), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',1,ref(11),[A,B,C,D,E,F,G,H,I,J]),use) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-medication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,'nonopioid-medication',countable), guideline_cardinality(actual,G,na,eq,1), guideline_property(actual,H,possible,pos), guideline_event(actual,I,be), guideline_arg(actual,I,1,G), guideline_arg(actual,I,2,H), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',1,ref(11),[A,B,C,D,E,F,G,H,I,J]),1,J) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-medication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,'nonopioid-medication',countable), guideline_cardinality(actual,G,na,eq,1), guideline_property(actual,H,possible,pos), guideline_event(actual,I,be), guideline_arg(actual,I,1,G), guideline_arg(actual,I,2,H), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',1,ref(11),[A,B,C,D,E,F,G,H,I,J]),2,G) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-medication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,'nonopioid-medication',countable), guideline_cardinality(actual,G,na,eq,1), guideline_property(actual,H,possible,pos), guideline_event(actual,I,be), guideline_arg(actual,I,1,G), guideline_arg(actual,I,2,H), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
% S2: If a patient has a long-term-opioid-use and needs an additional-opioid for an acute-pain then every clinician should limit the additional-opioid for an expected-severe-pain-duration and should restore a baseline-opioid-dosage.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(8),[A,B,C,D,E,F,G]),'expected-severe-pain-duration',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(9),[A,B,C,D,E,F,G]),limit) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(9),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(9),[A,B,C,D,E,F,G]),2,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(9),[A,B,C,D,E,F,G]),for,'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(2),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(10),[A,B,C,D,E,F,G]),'baseline-opioid-dosage',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(10),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(11),[A,B,C,D,E,F,G]),restore) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(11),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',2,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(11),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',2,ref(10),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'additional-opioid',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'acute-pain',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,need), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
% S3: If a patient has a long-term-opioid-use and has a prolonged-around-the-clock-additional-opioid-use for a few-day-period then every clinician should use a baseline-dosage-taper.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec01-imp04',3,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'prolonged-around-the-clock-additional-opioid-use',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'few-day-period',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',3,ref(8),[A,B,C,D,E,F,G]),'baseline-dosage-taper',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'prolonged-around-the-clock-additional-opioid-use',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'few-day-period',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',3,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'prolonged-around-the-clock-additional-opioid-use',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'few-day-period',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',3,ref(9),[A,B,C,D,E,F,G]),use) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'prolonged-around-the-clock-additional-opioid-use',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'few-day-period',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',3,ref(9),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'prolonged-around-the-clock-additional-opioid-use',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'few-day-period',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp04',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',3,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec01-imp04',3,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'prolonged-around-the-clock-additional-opioid-use',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'few-day-period',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
