% cdc2022-opioid-s47-18.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s47-18',ace_sha256('90583b73b35c62b5487e8fcc9383a158cee71a04c965f41713ef142963358758'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a pregnant-person has an undue-travel-burden for a neonatal-opioid-withdrawal-prepared-facility then every clinician should arrange a local-delivery for the pregnant-person.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-18',1,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,'pregnant-person',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'undue-travel-burden',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-prepared-facility',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-18',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s47-18',1,ref(6),[A,B,C,D,E]),'local-delivery',countable) :- guideline_entity(actual,A,'pregnant-person',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'undue-travel-burden',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-prepared-facility',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-18',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s47-18',1,ref(6),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,'pregnant-person',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'undue-travel-burden',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-prepared-facility',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-18',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s47-18',1,ref(7),[A,B,C,D,E]),arrange) :- guideline_entity(actual,A,'pregnant-person',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'undue-travel-burden',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-prepared-facility',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s47-18',1,ref(7),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,'pregnant-person',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'undue-travel-burden',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-prepared-facility',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s47-18',1,ref(7),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-s47-18',1,ref(6),[A,B,C,D,E])) :- guideline_entity(actual,A,'pregnant-person',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'undue-travel-burden',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-prepared-facility',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-18',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s47-18',1,ref(7),[A,B,C,D,E]),for,A) :- guideline_entity(actual,A,'pregnant-person',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'undue-travel-burden',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-prepared-facility',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
% S2: If a clinician arranges a local-delivery for a pregnant-person and the pregnant-person has a newborn then the clinician should monitor the newborn for a neonatal-opioid-withdrawal-syndrome and should evaluate the newborn for a neonatal-opioid-withdrawal-syndrome.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(7),[A,B,C,D,E,F]),'neonatal-opioid-withdrawal-syndrome',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(8),[A,B,C,D,E,F]),monitor) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(8),[A,B,C,D,E,F]),2,E) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(8),[A,B,C,D,E,F]),for,'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(9),[A,B,C,D,E,F]),'neonatal-opioid-withdrawal-syndrome',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(10),[A,B,C,D,E,F]),evaluate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(10),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(10),[A,B,C,D,E,F]),2,E) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-18',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(10),[A,B,C,D,E,F]),for,'$guideline_id'(product,'cdc2022-opioid-s47-18',2,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'local-delivery',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'pregnant-person',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,arrange), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,newborn,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
% S3: If a clinician monitors a newborn for a neonatal-opioid-withdrawal-syndrome and evaluates the newborn for the neonatal-opioid-withdrawal-syndrome and the newborn needs an additional-treatment then the clinician should transfer the newborn for the additional-treatment.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-18',3,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,newborn,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-syndrome',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,monitor), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,evaluate), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,C), guideline_entity(actual,F,'additional-treatment',countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,need), guideline_arg(actual,G,1,B), guideline_arg(actual,G,2,F).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-18',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s47-18',3,ref(8),[A,B,C,D,E,F,G]),transfer) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,newborn,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-syndrome',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,monitor), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,evaluate), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,C), guideline_entity(actual,F,'additional-treatment',countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,need), guideline_arg(actual,G,1,B), guideline_arg(actual,G,2,F).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s47-18',3,ref(8),[A,B,C,D,E,F,G]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,newborn,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-syndrome',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,monitor), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,evaluate), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,C), guideline_entity(actual,F,'additional-treatment',countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,need), guideline_arg(actual,G,1,B), guideline_arg(actual,G,2,F).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-18',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s47-18',3,ref(8),[A,B,C,D,E,F,G]),2,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,newborn,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-syndrome',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,monitor), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,evaluate), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,C), guideline_entity(actual,F,'additional-treatment',countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,need), guideline_arg(actual,G,1,B), guideline_arg(actual,G,2,F).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-18',3,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s47-18',3,ref(8),[A,B,C,D,E,F,G]),for,F) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,newborn,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'neonatal-opioid-withdrawal-syndrome',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,monitor), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,evaluate), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,C), guideline_entity(actual,F,'additional-treatment',countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,need), guideline_arg(actual,G,1,B), guideline_arg(actual,G,2,F).
