% cdc2022-opioid-s47-16.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s47-16',ace_sha256('4e7389f111261d58e92afd6abf8f87046183db6b9ae93efae039527c8662a46d'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If an infant has a long-term-opioid-exposure then every clinician should observe the infant for at least 72 hours and should monitor the infant for a withdrawal-development.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(5),[A,B,C,D]),hour,countable) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(5),[A,B,C,D]),na,geq,72) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(6),[A,B,C,D]),observe) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(6),[A,B,C,D]),2,A) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(6),[A,B,C,D]),for,'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(2),[A,B,C,D]),should) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(7),[A,B,C,D]),'withdrawal-development',countable) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(7),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(8),[A,B,C,D]),monitor) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(8),[A,B,C,D]),1,D) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(8),[A,B,C,D]),2,A) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-16',1,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(8),[A,B,C,D]),for,'$guideline_id'(product,'cdc2022-opioid-s47-16',1,ref(7),[A,B,C,D])) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S2: If an infant has a long-term-opioid-exposure and has a buprenorphine-exposure then every clinician should observe the infant for at least 4 days.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-16',2,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'buprenorphine-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-16',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',2,ref(7),[A,B,C,D,E,F]),day,countable) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'buprenorphine-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-16',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',2,ref(7),[A,B,C,D,E,F]),na,geq,4) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'buprenorphine-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-16',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',2,ref(8),[A,B,C,D,E,F]),observe) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'buprenorphine-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',2,ref(8),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'buprenorphine-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',2,ref(8),[A,B,C,D,E,F]),2,A) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'buprenorphine-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-16',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',2,ref(8),[A,B,C,D,E,F]),for,'$guideline_id'(product,'cdc2022-opioid-s47-16',2,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'buprenorphine-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
% S3: If an infant has a long-term-opioid-exposure and has an ER-LA-opioid-exposure then every clinician should observe the infant for at least 4 days.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-16',3,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'ER-LA-opioid-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-16',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',3,ref(7),[A,B,C,D,E,F]),day,countable) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'ER-LA-opioid-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-16',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',3,ref(7),[A,B,C,D,E,F]),na,geq,4) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'ER-LA-opioid-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-16',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',3,ref(8),[A,B,C,D,E,F]),observe) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'ER-LA-opioid-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',3,ref(8),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'ER-LA-opioid-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',3,ref(8),[A,B,C,D,E,F]),2,A) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'ER-LA-opioid-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-16',3,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',3,ref(8),[A,B,C,D,E,F]),for,'$guideline_id'(product,'cdc2022-opioid-s47-16',3,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'ER-LA-opioid-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
% S4: If an infant has a long-term-opioid-exposure and has a methadone-exposure then every clinician should observe the infant for at least 5 days.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s47-16',4,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'methadone-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s47-16',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',4,ref(7),[A,B,C,D,E,F]),day,countable) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'methadone-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s47-16',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',4,ref(7),[A,B,C,D,E,F]),na,geq,5) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'methadone-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s47-16',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',4,ref(8),[A,B,C,D,E,F]),observe) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'methadone-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',4,ref(8),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'methadone-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s47-16',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',4,ref(8),[A,B,C,D,E,F]),2,A) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'methadone-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s47-16',4,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s47-16',4,ref(8),[A,B,C,D,E,F]),for,'$guideline_id'(product,'cdc2022-opioid-s47-16',4,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,infant,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-exposure',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'methadone-exposure',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
