% cdc2022-opioid-rec09-imp05.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec09-imp05',ace_sha256('6c706171426cf6e702f14fa46a3ea730b156e17d7f976154d071f462e088ad3f'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a clinician reviews a controlled-substance-prescription-history with a state-PDMP-record for a patient then the clinician should interpret the controlled-substance-prescription-history with a patient-history.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp05',1,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',1,ref(6),[A,B,C,D,E]),'patient-history',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',1,ref(6),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',1,ref(7),[A,B,C,D,E]),interpret) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',1,ref(7),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',1,ref(7),[A,B,C,D,E]),2,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',1,ref(7),[A,B,C,D,E]),with,'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',1,ref(6),[A,B,C,D,E])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
% S2: If a clinician reviews a controlled-substance-prescription-history with a state-PDMP-record for a patient then the clinician should interpret the controlled-substance-prescription-history with a physical-finding.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp05',2,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',2,ref(6),[A,B,C,D,E]),'physical-finding',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',2,ref(6),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',2,ref(7),[A,B,C,D,E]),interpret) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',2,ref(7),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',2,ref(7),[A,B,C,D,E]),2,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',2,ref(7),[A,B,C,D,E]),with,'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',2,ref(6),[A,B,C,D,E])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
% S3: If a clinician reviews a controlled-substance-prescription-history with a state-PDMP-record for a patient then the clinician should interpret the controlled-substance-prescription-history with a relevant-testing.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp05',3,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',3,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',3,ref(6),[A,B,C,D,E]),'relevant-testing',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',3,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',3,ref(6),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',3,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',3,ref(7),[A,B,C,D,E]),interpret) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',3,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',3,ref(7),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',3,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',3,ref(7),[A,B,C,D,E]),2,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',3,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',3,ref(7),[A,B,C,D,E]),with,'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',3,ref(6),[A,B,C,D,E])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
% S4: If a clinician reviews a controlled-substance-prescription-history with a state-PDMP-record for a patient then the clinician should communicate with the patient and should protect the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',4,ref(6),[A,B,C,D,E]),communicate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',4,ref(6),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',4,ref(6),[A,B,C,D,E]),with,D) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(2),[A,B,C,D,E]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',4,ref(7),[A,B,C,D,E]),protect) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',4,ref(7),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp05',4,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp05',4,ref(7),[A,B,C,D,E]),2,D) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'controlled-substance-prescription-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,review), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,with,C).
