% cdc2022-opioid-rec09-imp10.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec09-imp10',ace_sha256(cfe85cc4570a8e24e5e865213ab5018a78a9948914f3f410b17f4c85337c8b1c),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a clinician identifies an additional-prescription in a state-PDMP-record for a patient then the clinician should discuss the state-PDMP-record with the patient and should confirm an additional-prescription-awareness with the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(6),[A,B,C,D,E]),discuss) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(6),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(6),[A,B,C,D,E]),2,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(6),[A,B,C,D,E]),with,D) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(2),[A,B,C,D,E]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(7),[A,B,C,D,E]),'additional-prescription-awareness',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(7),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(8),[A,B,C,D,E]),confirm) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(8),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(8),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(7),[A,B,C,D,E])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp10',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp10',1,ref(8),[A,B,C,D,E]),with,D) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'additional-prescription',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'state-PDMP-record',countable), guideline_cardinality(actual,C,na,eq,1), guideline_entity(actual,D,patient,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,identify), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_pp(actual,E,for,D), guideline_pp(actual,E,in,C).
