% cdc2022-opioid-rec09-imp22.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec09-imp22',ace_sha256(a1c8cca6023ee4333a2c21255f6d64d8807307d93f2075b89e7562894a653fc6),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a patient has a negative-toxicology-test for a prescribed-opioid then the negative-toxicology-test may indicate a prescribed-opioid-nonuse for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp22',1,box(1),[A,B,C,D]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',1,ref(5),[A,B,C,D]),'prescribed-opioid-nonuse',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',1,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',1,ref(6),[A,B,C,D]),indicate) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',1,ref(6),[A,B,C,D]),1,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',1,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',1,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',1,ref(6),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
% S2: If a patient has a negative-toxicology-test for a prescribed-opioid and a clinician reviews the negative-toxicology-test then the clinician should consider a false-negative-test-result and should consider a test-result-misinterpretation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(7),[A,B,C,D,E,F]),'false-negative-test-result',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(8),[A,B,C,D,E,F]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(8),[A,B,C,D,E,F]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(9),[A,B,C,D,E,F]),'test-result-misinterpretation',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(10),[A,B,C,D,E,F]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(10),[A,B,C,D,E,F]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp22',2,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp22',2,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'negative-toxicology-test',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'prescribed-opioid',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,review), guideline_arg(actual,F,1,E), guideline_arg(actual,F,2,B).
