% cdc2022-opioid-rec11-imp05.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec11-imp05',ace_sha256('439d06fca4d30a74c01f68bea16c875ed15a7aba9039d27696acab78f398b559'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a patient has a long-term-opioid-and-benzodiazepine-therapy and a clinician considers a concurrent-therapy-continuation-decision for the patient then the clinician should weigh a benefit against a risk during the concurrent-therapy-continuation-decision and should discuss the concurrent-therapy-continuation-decision with the patient and should discuss the concurrent-therapy-continuation-decision with a patient-care-team-member.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(7),[A,B,C,D,E,F]),benefit,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(8),[A,B,C,D,E,F]),risk,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(8),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(9),[A,B,C,D,E,F]),weigh) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(9),[A,B,C,D,E,F]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(9),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(9),[A,B,C,D,E,F]),during,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(9),[A,B,C,D,E,F]),against,'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(8),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(10),[A,B,C,D,E,F]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(10),[A,B,C,D,E,F]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(10),[A,B,C,D,E,F]),2,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(10),[A,B,C,D,E,F]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(3),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(11),[A,B,C,D,E,F]),'patient-care-team-member',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(11),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(12),[A,B,C,D,E,F]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(12),[A,B,C,D,E,F]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(12),[A,B,C,D,E,F]),2,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec11-imp05',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(12),[A,B,C,D,E,F]),with,'$guideline_id'(product,'cdc2022-opioid-rec11-imp05',1,ref(11),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'long-term-opioid-and-benzodiazepine-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'concurrent-therapy-continuation-decision',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,consider), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,A).
