% cdc2022-opioid-s60-16.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s60-16',ace_sha256(a8476ba290c3c6d772b1d1a14a68c02ddceed2a0bd512c67316ed79a6438e568),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a clinician treats a patient in a supervised-setting and the patient receives a regular-buprenorphine-dosage then the clinician may add a short-acting-full-agonist-opioid to the regular-buprenorphine-dosage for the patient and may continue the regular-buprenorphine-dosage for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),may) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(7),[A,B,C,D,E,F]),'short-acting-full-agonist-opioid',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(8),[A,B,C,D,E,F]),add) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(8),[A,B,C,D,E,F]),for,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(8),[A,B,C,D,E,F]),to,E) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(2),[A,B,C,D,E,F]),may) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(9),[A,B,C,D,E,F]),continue) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(9),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(9),[A,B,C,D,E,F]),2,E) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-16',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-16',1,ref(9),[A,B,C,D,E,F]),for,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'supervised-setting',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,treat), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,in,C), guideline_entity(actual,E,'regular-buprenorphine-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,receive), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E).
% S2: If a clinician makes a buprenorphine-discontinuation-decision for a patient then the clinician should conduct a close-patient-monitoring for the patient and should monitor the patient for an oversedation and should monitor the patient for a respiratory-depression.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(5),[A,B,C,D]),'close-patient-monitoring',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(6),[A,B,C,D]),conduct) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(6),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(6),[A,B,C,D]),for,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(2),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(7),[A,B,C,D]),oversedation,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(7),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(8),[A,B,C,D]),monitor) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(8),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(8),[A,B,C,D]),2,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(8),[A,B,C,D]),for,'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(7),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(3),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(9),[A,B,C,D]),'respiratory-depression',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(9),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(10),[A,B,C,D]),monitor) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(10),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(10),[A,B,C,D]),2,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-16',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(10),[A,B,C,D]),for,'$guideline_id'(product,'cdc2022-opioid-s60-16',2,ref(9),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'buprenorphine-discontinuation-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,make), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C).
