% cdc2022-opioid-s39-01.pl compiled from ACE by ace_to_pl; regenerate via ckc compile; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/4).
:- discontiguous(guideline_document/4).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
:- multifile(guideline_interval/6).
:- discontiguous(guideline_interval/6).
:- multifile(guideline_recurrence/4).
:- discontiguous(guideline_recurrence/4).
:- multifile(guideline_frequency/5).
:- discontiguous(guideline_frequency/5).
:- multifile(guideline_order/4).
:- discontiguous(guideline_order/4).
:- multifile(guideline_recurrence_window/7).
:- discontiguous(guideline_recurrence_window/7).
:- multifile(guideline_range/3).
:- discontiguous(guideline_range/3).
guideline_schema_version(3).
guideline_document('cdc2022-opioid-s39-01',ace_sha256(d9ba9ab51d54d9123ab10a50b1b6dbd46896600cf08feb7f5b8d43bcbd17d769),ulex(sha256('0b669018d532f506c518a6b0edffa4994f771b930477e7e2b36faf50d2b75d33')),temporal(sha256(d7b0d6c9af49f8d4b3dc12370d6b1cc20e923a69a5ce745ee26a1bc0f21effb6))).
% S1: If a patient has a shorter-duration-opioid-use then every clinician may use a ten-percent-of-original-dose-per-week-or-slower-first-taper-stage for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s39-01',1,box(1),[A,B,C,D]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s39-01',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s39-01',1,ref(5),[A,B,C,D]),'ten-percent-of-original-dose-per-week-or-slower-first-taper-stage',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s39-01',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s39-01',1,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s39-01',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s39-01',1,ref(6),[A,B,C,D]),use) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s39-01',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s39-01',1,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s39-01',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s39-01',1,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s39-01',1,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s39-01',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s39-01',1,ref(6),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S2: If a patient has a shorter-duration-opioid-use and the patient reaches an approximately-thirty-percent-of-original-dose then every clinician may decrease a remaining-opioid-dose by an approximately-ten-percent at an interval of 1 week for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(7),[A,B,C,D,E,F]),'remaining-opioid-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(8),[A,B,C,D,E,F]),'approximately-ten-percent',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(8),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(9),[A,B,C,D,E,F]),interval,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(10),[A,B,C,D,E,F]),week,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(10),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(11),[A,B,C,D,E,F]),decrease) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(11),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(11),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(11),[A,B,C,D,E,F]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(11),[A,B,C,D,E,F]),at,'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_recurrence('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(11),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(10),[A,B,C,D,E,F]),week) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s39-01',2,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(11),[A,B,C,D,E,F]),by,'$guideline_id'(product,'cdc2022-opioid-s39-01',2,ref(8),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'shorter-duration-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'approximately-thirty-percent-of-original-dose',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,reach), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
