% cdc2022-opioid-rec11-imp08.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec11-imp08',ace_sha256('97cebd06f7719290500a280ce80734107e30bc54973e143f98f269710e82b575'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: Every evidence-based-psychotherapy is a nonbenzodiazepine-anxiety-treatment.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',1,ref(2),[A]),'nonbenzodiazepine-anxiety-treatment',countable) :- guideline_entity(actual,A,'evidence-based-psychotherapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'evidence-based-psychotherapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',1,ref(3),[A]),be) :- guideline_entity(actual,A,'evidence-based-psychotherapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',1,ref(3),[A]),1,A) :- guideline_entity(actual,A,'evidence-based-psychotherapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',1,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',1,ref(2),[A])) :- guideline_entity(actual,A,'evidence-based-psychotherapy',countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every specific-antidepressant is a nonbenzodiazepine-anxiety-treatment.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',2,ref(2),[A]),'nonbenzodiazepine-anxiety-treatment',countable) :- guideline_entity(actual,A,'specific-antidepressant',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'specific-antidepressant',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',2,ref(3),[A]),be) :- guideline_entity(actual,A,'specific-antidepressant',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',2,ref(3),[A]),1,A) :- guideline_entity(actual,A,'specific-antidepressant',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',2,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',2,ref(2),[A])) :- guideline_entity(actual,A,'specific-antidepressant',countable), guideline_cardinality(actual,A,na,eq,1).
% S3: Every anxiety-approved-nonbenzodiazepine-medication is a nonbenzodiazepine-anxiety-treatment.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',3,ref(2),[A]),'nonbenzodiazepine-anxiety-treatment',countable) :- guideline_entity(actual,A,'anxiety-approved-nonbenzodiazepine-medication',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',3,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'anxiety-approved-nonbenzodiazepine-medication',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',3,ref(3),[A]),be) :- guideline_entity(actual,A,'anxiety-approved-nonbenzodiazepine-medication',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',3,ref(3),[A]),1,A) :- guideline_entity(actual,A,'anxiety-approved-nonbenzodiazepine-medication',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',3,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',3,ref(2),[A])) :- guideline_entity(actual,A,'anxiety-approved-nonbenzodiazepine-medication',countable), guideline_cardinality(actual,A,na,eq,1).
% S4: Every cognitive-behavioral-therapy is an evidence-based-psychotherapy.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',4,ref(2),[A]),'evidence-based-psychotherapy',countable) :- guideline_entity(actual,A,'cognitive-behavioral-therapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',4,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'cognitive-behavioral-therapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',4,ref(3),[A]),be) :- guideline_entity(actual,A,'cognitive-behavioral-therapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',4,ref(3),[A]),1,A) :- guideline_entity(actual,A,'cognitive-behavioral-therapy',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',4,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',4,ref(2),[A])) :- guideline_entity(actual,A,'cognitive-behavioral-therapy',countable), guideline_cardinality(actual,A,na,eq,1).
% S5: If a patient has an anxiety and receives a benzodiazepine for the anxiety and a clinician tapers the benzodiazepine for the patient then the clinician should offer a nonbenzodiazepine-anxiety-treatment to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec11-imp08',5,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,taper), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',5,ref(8),[A,B,C,D,E,F,G]),'nonbenzodiazepine-anxiety-treatment',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,taper), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',5,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,taper), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',5,ref(9),[A,B,C,D,E,F,G]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,taper), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',5,ref(9),[A,B,C,D,E,F,G]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,taper), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',5,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',5,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,taper), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',5,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',5,ref(9),[A,B,C,D,E,F,G]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,taper), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
% S6: If a patient has an anxiety and receives a benzodiazepine for the anxiety and a clinician discontinues the benzodiazepine for the patient then the clinician should offer a nonbenzodiazepine-anxiety-treatment to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec11-imp08',6,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,discontinue), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',6,ref(8),[A,B,C,D,E,F,G]),'nonbenzodiazepine-anxiety-treatment',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,discontinue), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',6,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,discontinue), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',6,ref(9),[A,B,C,D,E,F,G]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,discontinue), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',6,ref(9),[A,B,C,D,E,F,G]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,discontinue), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',6,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',6,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,discontinue), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',6,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',6,ref(9),[A,B,C,D,E,F,G]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,anxiety,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,benzodiazepine,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,receive), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_pp(actual,E,for,B), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1), guideline_event(actual,G,discontinue), guideline_arg(actual,G,1,F), guideline_arg(actual,G,2,D), guideline_pp(actual,G,for,A).
% S7: If a patient receives an opioid and requires an anxiety-treatment then every clinician should offer a nonbenzodiazepine-anxiety-treatment to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec11-imp08',7,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'anxiety-treatment',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,require), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',7,ref(7),[A,B,C,D,E,F]),'nonbenzodiazepine-anxiety-treatment',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'anxiety-treatment',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,require), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',7,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'anxiety-treatment',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,require), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',7,ref(8),[A,B,C,D,E,F]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'anxiety-treatment',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,require), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',7,ref(8),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'anxiety-treatment',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,require), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',7,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',7,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'anxiety-treatment',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,require), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec11-imp08',7,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec11-imp08',7,ref(8),[A,B,C,D,E,F]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'anxiety-treatment',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,require), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
