% cdc2022-opioid-s26-01.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s26-01',ace_sha256(efe64f9ef9596489c20c0600fe981969995f5344cbef933cfc95dcdf53547be9),ulex(sha256(ef57ba7180864095bab88b95f11ddb1a2c858593eba715dbfbe874db09506c5b))).
% S1: If an active-nonpharmacologic-approach has a patient-engagement and is possible then every clinician should use the active-nonpharmacologic-approach and should reserve a passive-nonpharmacologic-approach for a supplementary-role.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(7),[A,B,C,D,E,F]),use) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(7),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(7),[A,B,C,D,E,F]),2,A) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(8),[A,B,C,D,E,F]),'passive-nonpharmacologic-approach',countable) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(8),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(9),[A,B,C,D,E,F]),'supplementary-role',countable) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(10),[A,B,C,D,E,F]),reserve) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(10),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(8),[A,B,C,D,E,F])) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s26-01',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(10),[A,B,C,D,E,F]),for,'$guideline_id'(product,'cdc2022-opioid-s26-01',1,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,'active-nonpharmacologic-approach',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'patient-engagement',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_property(actual,D,possible,pos), guideline_event(actual,E,be), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
