% cdc2022-opioid-rec07-imp03.pl compiled from ACE by ace_to_pl; regenerate via ckc compile; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/4).
:- discontiguous(guideline_document/4).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
:- multifile(guideline_interval/6).
:- discontiguous(guideline_interval/6).
:- multifile(guideline_recurrence/4).
:- discontiguous(guideline_recurrence/4).
:- multifile(guideline_frequency/5).
:- discontiguous(guideline_frequency/5).
:- multifile(guideline_order/4).
:- discontiguous(guideline_order/4).
:- multifile(guideline_recurrence_window/7).
:- discontiguous(guideline_recurrence_window/7).
:- multifile(guideline_range/3).
:- discontiguous(guideline_range/3).
guideline_schema_version(3).
guideline_document('cdc2022-opioid-rec07-imp03',ace_sha256(eacef80acd9c77d1acbb5610c815607c87ed2b4106c6181a4b367c7d38e380c0),ulex(sha256('0b669018d532f506c518a6b0edffa4994f771b930477e7e2b36faf50d2b75d33')),temporal(sha256(d7b0d6c9af49f8d4b3dc12370d6b1cc20e923a69a5ce745ee26a1bc0f21effb6))).
% S1: If a clinician starts an immediate-release-opioid for a patient and the immediate-release-opioid has an opioid-dosage and the opioid-dosage includes less than 50 MME-units-per-day then the clinician may conduct an initial-follow-up with the patient after 4 approximate weeks of a therapy-start.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),may) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(9),[A,B,C,D,E,F,G,H]),'initial-follow-up',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(9),[A,B,C,D,E,F,G,H]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(10),[A,B,C,D,E,F,G,H]),week,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(10),[A,B,C,D,E,F,G,H]),na,about,4) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_property('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(10),[A,B,C,D,E,F,G,H]),approximate,pos) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(11),[A,B,C,D,E,F,G,H]),'therapy-start',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(11),[A,B,C,D,E,F,G,H]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(12),[A,B,C,D,E,F,G,H]),conduct) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(12),[A,B,C,D,E,F,G,H]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(12),[A,B,C,D,E,F,G,H]),2,'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(9),[A,B,C,D,E,F,G,H])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(12),[A,B,C,D,E,F,G,H]),after,'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(10),[A,B,C,D,E,F,G,H])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_interval('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(12),[A,B,C,D,E,F,G,H]),after,'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(10),[A,B,C,D,E,F,G,H]),week,'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(11),[A,B,C,D,E,F,G,H])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec07-imp03',1,box(1),[A,B,C,D,E,F,G,H]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp03',1,ref(12),[A,B,C,D,E,F,G,H]),with,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'immediate-release-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,start), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_entity(actual,E,'opioid-dosage',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,'MME-unit-per-day',countable), guideline_cardinality(actual,G,na,less,50).
