% cdc2022-opioid-rec09-imp12.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec09-imp12',ace_sha256('7ec6d93eac3fcdb7068ee69c8ab9b7c857068d6166293133a0f330e9aaca4717'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a patient receives at least 2 overlapping-prescribed-opioids from at least 2 clinicians and the clinicians do not coordinate a care for the patient then every clinician should discuss an increased-respiratory-depression-risk with the patient and should discuss an increased-overdose-risk with the patient and should offer a naloxone-dose to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(2),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(8),[A,B,C,D,E]),'increased-respiratory-depression-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(8),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(9),[A,B,C,D,E]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(9),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(9),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(8),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(9),[A,B,C,D,E]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(3),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(10),[A,B,C,D,E]),'increased-overdose-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(10),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(11),[A,B,C,D,E]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(11),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(11),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(10),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(11),[A,B,C,D,E]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(4),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(12),[A,B,C,D,E]),'naloxone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(12),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(13),[A,B,C,D,E]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(13),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(13),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(12),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',1,box(4),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',1,ref(13),[A,B,C,D,E]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overlapping-prescribed-opioid',countable), guideline_cardinality(actual,B,na,geq,2), guideline_entity(actual,C,clinician,countable), guideline_cardinality(actual,C,na,geq,2), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_operator(actual,F,-), guideline_entity(F,G,care,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,coordinate), guideline_arg(F,H,1,C), guideline_arg(F,H,2,G), guideline_pp(F,H,for,A), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
% S2: If a patient receives an opioid-combination-risk-increasing-medication then every clinician should discuss an increased-respiratory-depression-risk with the patient and should discuss an increased-overdose-risk with the patient and should offer a naloxone-dose to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(5),[A,B,C,D]),'increased-respiratory-depression-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(6),[A,B,C,D]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(6),[A,B,C,D]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(2),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(7),[A,B,C,D]),'increased-overdose-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(7),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(8),[A,B,C,D]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(8),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(8),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(7),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(8),[A,B,C,D]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(3),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(9),[A,B,C,D]),'naloxone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(9),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(10),[A,B,C,D]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(10),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(10),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(9),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp12',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp12',2,ref(10),[A,B,C,D]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-combination-risk-increasing-medication',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,receive), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
