% cdc2022-opioid-rec10-imp10.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec10-imp10',ace_sha256('62022ed0143cdb1020f9965e44ca484262e25a4049c40fd692f08966d050ed6e'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a toxicology-test-result informs a clinical-decision and the clinical-decision has a major-implication for a patient then every clinician should use a confirmatory-testing for the toxicology-test-result.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp10',1,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'clinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',1,ref(8),[A,B,C,D,E,F,G]),'confirmatory-testing',countable) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'clinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',1,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'clinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',1,ref(9),[A,B,C,D,E,F,G]),use) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'clinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',1,ref(9),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'clinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',1,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',1,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'clinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',1,ref(9),[A,B,C,D,E,F,G]),for,A) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'clinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
% S2: If a toxicology-test-result informs a nonclinical-decision and the nonclinical-decision has a major-implication for a patient then every clinician should use a confirmatory-testing for the toxicology-test-result.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp10',2,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'nonclinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',2,ref(8),[A,B,C,D,E,F,G]),'confirmatory-testing',countable) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'nonclinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',2,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'nonclinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',2,ref(9),[A,B,C,D,E,F,G]),use) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'nonclinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',2,ref(9),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'nonclinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',2,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',2,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'nonclinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',2,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',2,ref(9),[A,B,C,D,E,F,G]),for,A) :- guideline_entity(actual,A,'toxicology-test-result',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'nonclinical-decision',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,inform), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'major-implication',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,patient,countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,B), guideline_arg(actual,F,2,D), guideline_pp(actual,F,for,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
% S3: If a clinician needs a specific-opioid-detection then the clinician should use a confirmatory-testing.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp10',3,box(1),[A,B,C]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'specific-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',3,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',3,ref(4),[A,B,C]),'confirmatory-testing',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'specific-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',3,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',3,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'specific-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',3,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',3,ref(5),[A,B,C]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'specific-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',3,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',3,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'specific-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',3,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',3,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',3,ref(4),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'specific-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S4: If a clinician needs a prescribed-opioid-detection then the clinician should use a confirmatory-testing.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp10',4,box(1),[A,B,C]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'prescribed-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',4,ref(4),[A,B,C]),'confirmatory-testing',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'prescribed-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',4,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'prescribed-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',4,ref(5),[A,B,C]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'prescribed-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',4,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'prescribed-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',4,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',4,ref(4),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'prescribed-opioid-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S5: If a clinician needs a within-class-drug-detection then the clinician should use a confirmatory-testing.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp10',5,box(1),[A,B,C]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'within-class-drug-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',5,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',5,ref(4),[A,B,C]),'confirmatory-testing',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'within-class-drug-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',5,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',5,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'within-class-drug-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',5,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',5,ref(5),[A,B,C]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'within-class-drug-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',5,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',5,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'within-class-drug-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',5,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',5,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',5,ref(4),[A,B,C])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'within-class-drug-detection',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,need), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S6: If a clinician considers a drug and a standard-immunoassay does not identify the drug then the clinician should use a confirmatory-testing for the drug.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp10',6,box(2),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,drug,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,consider), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'standard-immunoassay',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,E,-), guideline_event(E,F,identify), guideline_arg(E,F,1,D), guideline_arg(E,F,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',6,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',6,ref(6),[A,B,C,D]),'confirmatory-testing',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,drug,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,consider), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'standard-immunoassay',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,E,-), guideline_event(E,F,identify), guideline_arg(E,F,1,D), guideline_arg(E,F,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',6,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',6,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,drug,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,consider), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'standard-immunoassay',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,E,-), guideline_event(E,F,identify), guideline_arg(E,F,1,D), guideline_arg(E,F,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',6,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',6,ref(7),[A,B,C,D]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,drug,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,consider), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'standard-immunoassay',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,E,-), guideline_event(E,F,identify), guideline_arg(E,F,1,D), guideline_arg(E,F,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',6,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',6,ref(7),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,drug,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,consider), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'standard-immunoassay',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,E,-), guideline_event(E,F,identify), guideline_arg(E,F,1,D), guideline_arg(E,F,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',6,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',6,ref(7),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',6,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,drug,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,consider), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'standard-immunoassay',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,E,-), guideline_event(E,F,identify), guideline_arg(E,F,1,D), guideline_arg(E,F,2,B).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',6,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',6,ref(7),[A,B,C,D]),for,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,drug,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,consider), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'standard-immunoassay',countable), guideline_cardinality(actual,D,na,eq,1), guideline_operator(actual,E,-), guideline_event(E,F,identify), guideline_arg(E,F,1,D), guideline_arg(E,F,2,B).
% S7: If a patient has an unexpected-screening-toxicology-test-result then every clinician should use a confirmatory-testing for the unexpected-screening-toxicology-test-result.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp10',7,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-screening-toxicology-test-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',7,ref(5),[A,B,C,D]),'confirmatory-testing',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-screening-toxicology-test-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',7,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-screening-toxicology-test-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',7,ref(6),[A,B,C,D]),use) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-screening-toxicology-test-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',7,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-screening-toxicology-test-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',7,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',7,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-screening-toxicology-test-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp10',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp10',7,ref(6),[A,B,C,D]),for,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-screening-toxicology-test-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
