% cdc2022-opioid-rec07-imp08.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec07-imp08',ace_sha256('41c4f8dce9a0412e4f90c0206d22546af4f9287ad6d25b29d7b8d567690a850a'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a patient has a depression then the patient has a higher-opioid-harm-risk.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',1,ref(4),[A,B,C]),'higher-opioid-harm-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,depression,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',1,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,depression,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',1,ref(5),[A,B,C]),have) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,depression,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',1,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,depression,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',1,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',1,ref(4),[A,B,C])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,depression,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S2: If a patient has a mental-health-condition then the patient has a higher-opioid-harm-risk.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',2,ref(4),[A,B,C]),'higher-opioid-harm-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mental-health-condition',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',2,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mental-health-condition',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',2,ref(5),[A,B,C]),have) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mental-health-condition',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',2,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mental-health-condition',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',2,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',2,ref(4),[A,B,C])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mental-health-condition',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S3: If a patient has a substance-use-disorder-history then the patient has a higher-opioid-harm-risk.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',3,ref(4),[A,B,C]),'higher-opioid-harm-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',3,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',3,ref(5),[A,B,C]),have) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',3,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',3,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',3,ref(4),[A,B,C])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S4: If a patient has an overdose-history then the patient has a higher-opioid-harm-risk.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',4,ref(4),[A,B,C]),'higher-opioid-harm-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',4,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',4,ref(5),[A,B,C]),have) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',4,ref(5),[A,B,C]),1,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',4,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',4,ref(4),[A,B,C])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-history',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S5: If a patient has a combined-opioid-dosage and the combined-opioid-dosage includes at least 50 MME-units-per-day then the patient has a higher-opioid-harm-risk.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',5,ref(6),[A,B,C,D,E]),'higher-opioid-harm-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',5,ref(6),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',5,ref(7),[A,B,C,D,E]),have) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',5,ref(7),[A,B,C,D,E]),1,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',5,ref(7),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',5,ref(6),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D).
% S6: If a patient takes a central-nervous-system-depressant with an opioid then the patient has a higher-opioid-harm-risk.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',6,ref(5),[A,B,C,D]),'higher-opioid-harm-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'central-nervous-system-depressant',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,opioid,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,take), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,with,C).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',6,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'central-nervous-system-depressant',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,opioid,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,take), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,with,C).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',6,ref(6),[A,B,C,D]),have) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'central-nervous-system-depressant',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,opioid,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,take), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,with,C).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',6,ref(6),[A,B,C,D]),1,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'central-nervous-system-depressant',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,opioid,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,take), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,with,C).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',6,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',6,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'central-nervous-system-depressant',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,opioid,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,take), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,with,C).
% S7: If a patient has a higher-opioid-harm-risk and a higher-risk-opioid-reevaluation-schedule has a reevaluation-interval and the reevaluation-interval includes less than 3 months then every clinician should use the higher-risk-opioid-reevaluation-schedule for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec07-imp08',7,box(1),[A,B,C,D,E,F,G,H,I]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'higher-opioid-harm-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'higher-risk-opioid-reevaluation-schedule',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'reevaluation-interval',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,month,countable), guideline_cardinality(actual,G,na,less,3), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec07-imp08',7,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',7,ref(10),[A,B,C,D,E,F,G,H,I]),use) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'higher-opioid-harm-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'higher-risk-opioid-reevaluation-schedule',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'reevaluation-interval',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,month,countable), guideline_cardinality(actual,G,na,less,3), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec07-imp08',7,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',7,ref(10),[A,B,C,D,E,F,G,H,I]),1,I) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'higher-opioid-harm-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'higher-risk-opioid-reevaluation-schedule',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'reevaluation-interval',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,month,countable), guideline_cardinality(actual,G,na,less,3), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec07-imp08',7,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',7,ref(10),[A,B,C,D,E,F,G,H,I]),2,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'higher-opioid-harm-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'higher-risk-opioid-reevaluation-schedule',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'reevaluation-interval',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,month,countable), guideline_cardinality(actual,G,na,less,3), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec07-imp08',7,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-rec07-imp08',7,ref(10),[A,B,C,D,E,F,G,H,I]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'higher-opioid-harm-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'higher-risk-opioid-reevaluation-schedule',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'reevaluation-interval',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_event(actual,H,include), guideline_arg(actual,H,1,E), guideline_arg(actual,H,2,G), guideline_entity(actual,G,month,countable), guideline_cardinality(actual,G,na,less,3), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
