% cdc2022-opioid-s60-13.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s60-13',ace_sha256(b7c9221ffa1f898b5b9a04efb62a6d34288dfe5de8813498d30f8ef9d216d7a8),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a patient has a pain and has an active-opioid-use-disorder and does not receive an opioid-use-disorder-treatment then every clinician should consider a buprenorphine-treatment for the patient and should consider a methadone-treatment for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(9),[A,B,C,D,E,F]),'buprenorphine-treatment',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(10),[A,B,C,D,E,F]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(10),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(10),[A,B,C,D,E,F]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(3),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(11),[A,B,C,D,E,F]),'methadone-treatment',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(11),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(12),[A,B,C,D,E,F]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(12),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(12),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(11),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s60-13',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s60-13',1,ref(12),[A,B,C,D,E,F]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,pain,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'active-opioid-use-disorder',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_operator(actual,G,-), guideline_entity(G,H,'opioid-use-disorder-treatment',countable), guideline_cardinality(G,H,na,eq,1), guideline_event(G,I,receive), guideline_arg(G,I,1,A), guideline_arg(G,I,2,H), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
