% cdc2022-opioid-rec10-imp03.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec10-imp03',ace_sha256(c4414ef7cdad455df6b6fa51a3541b2f6dc6f0297d012c1f5e569165c71bd95d),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: Every clinician should consider a testing-benefit before an opioid-initiation and should consider a testing-risk before an opioid-initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(2),[A]),'testing-benefit',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(3),[A]),'opioid-initiation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(4),[A]),consider) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(4),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(5),[A]),'testing-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(5),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(6),[A]),'opioid-initiation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(6),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(7),[A]),consider) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(7),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(7),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(5),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(7),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',1,ref(6),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S2: If a patient receives an opioid-therapy during a year then every clinician should consider a testing-benefit during the year and should consider a testing-risk during the year.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(6),[A,B,C,D,E]),'testing-benefit',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(6),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(7),[A,B,C,D,E]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(7),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(7),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(6),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(7),[A,B,C,D,E]),during,C) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(2),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(8),[A,B,C,D,E]),'testing-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(8),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(9),[A,B,C,D,E]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(9),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(9),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(8),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',2,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',2,ref(9),[A,B,C,D,E]),during,C) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-therapy',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,year,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
% S3: A toxicology-testing can assess a prescribed-opioid and can assess a prescribed-controlled-substance and can assess a nonprescribed-controlled-substance and can assess a nonprescribed-opioid and can assess an illicit-opioid and can assess a benzodiazepine.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[]),'toxicology-testing',countable).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[]),na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(1),[]),can).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(1),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(2),[]),'prescribed-opioid',countable).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(1),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(2),[]),na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(1),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(3),[]),assess).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(1),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(3),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[])).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(1),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(3),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(2),[])).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(2),[]),can).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(2),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(4),[]),'prescribed-controlled-substance',countable).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(2),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(4),[]),na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(2),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(5),[]),assess).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(2),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(5),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[])).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(2),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(5),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(4),[])).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(3),[]),can).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(3),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(6),[]),'nonprescribed-controlled-substance',countable).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(3),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(6),[]),na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(3),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(7),[]),assess).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(3),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(7),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[])).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(3),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(7),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(6),[])).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(4),[]),can).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(4),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(8),[]),'nonprescribed-opioid',countable).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(4),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(8),[]),na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(4),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(9),[]),assess).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(4),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(9),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[])).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(4),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(9),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(8),[])).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(5),[]),can).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(5),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(10),[]),'illicit-opioid',countable).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(5),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(10),[]),na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(5),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(11),[]),assess).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(5),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(11),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[])).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(5),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(11),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(10),[])).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(6),[]),can).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(6),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(12),[]),benzodiazepine,countable).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(6),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(12),[]),na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(6),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(13),[]),assess).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(6),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(13),[]),1,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(1),[])).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp03',3,box(6),[]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(13),[]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp03',3,ref(12),[])).
