% cdc2022-opioid-s38-12.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s38-12',ace_sha256(e4682b8f6271a41ce647162acdf8846149c3a898091e2622d4bfb7ca22f8dc52),ulex(sha256('2a4a3e829c919b3dd3b20356e7a69585cfb305c3c57dfb531e3f2c1eb97637b6'))).
% S1: If a patient has a serious-mental-illness and the patient has a high-suicide-risk then every clinician should consider a behavioral-health-specialist-consultation before an opioid-taper-initiation for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(7),[A,B,C,D,E,F]),'behavioral-health-specialist-consultation',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(8),[A,B,C,D,E,F]),'opioid-taper-initiation',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(8),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(9),[A,B,C,D,E,F]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(9),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(9),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(9),[A,B,C,D,E,F]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-12',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(9),[A,B,C,D,E,F]),before,'$guideline_id'(product,'cdc2022-opioid-s38-12',1,ref(8),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'serious-mental-illness',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'high-suicide-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
% S2: If a patient has a suicidal-ideation then every clinician should consider a behavioral-health-specialist-consultation before an opioid-taper-initiation for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(5),[A,B,C,D]),'behavioral-health-specialist-consultation',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(6),[A,B,C,D]),'opioid-taper-initiation',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(7),[A,B,C,D]),consider) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(7),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(7),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(7),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-12',2,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(7),[A,B,C,D]),before,'$guideline_id'(product,'cdc2022-opioid-s38-12',2,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'suicidal-ideation',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
