% cdc2022-opioid-rec08-imp15.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec08-imp15',ace_sha256('6c022c14eb832cdb779b9eca5c3a0a2efdb86a89f7d74fd13145ea3fdbecd5ee'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: Every clinician should assess a concurrent-substance-use.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp15',1,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',1,ref(2),[A]),'concurrent-substance-use',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',1,ref(3),[A]),assess) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',1,ref(3),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',1,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',1,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every clinician should use a state-PDMP-record during a concurrent-substance-use-assessment.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(2),[A]),'state-PDMP-record',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(3),[A]),'concurrent-substance-use-assessment',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(4),[A]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(4),[A]),during,'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',2,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S3: Every clinician should use a toxicology-testing during a concurrent-substance-use-assessment.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(2),[A]),'toxicology-testing',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(3),[A]),'concurrent-substance-use-assessment',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(4),[A]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(4),[A]),during,'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',3,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S4: If a patient has a concurrent-substance-use then the concurrent-substance-use can increase an opioid-use-disorder-risk for the patient and can increase an overdose-risk for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(1),[A,B,C]),can) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(4),[A,B,C]),'opioid-use-disorder-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(5),[A,B,C]),increase) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(5),[A,B,C]),1,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(5),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(4),[A,B,C])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(1),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(5),[A,B,C]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(2),[A,B,C]),can) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(2),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(6),[A,B,C]),'overdose-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(2),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(6),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(2),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(7),[A,B,C]),increase) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(2),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(7),[A,B,C]),1,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(2),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(7),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(6),[A,B,C])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec08-imp15',4,box(2),[A,B,C]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp15',4,ref(7),[A,B,C]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'concurrent-substance-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
