% cdc2022-opioid-rec01-imp02.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec01-imp02',ace_sha256('827a00f98cf682a8da35fcff8042c867380d23707454ddfe780f52bb84ae81c0'),ulex(sha256(e099ebb206cfb62cc396438935bd812a79998ee738ec876290f34a554836093e))).
% S1: If an acute-pain-diagnosis warrants an opioid-use and an acute-pain-severity warrants an opioid-use then every clinician should prescribe an immediate-release-opioid at a lowest-effective-dose for an expected-severe-pain-duration.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),should) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(8),[A,B,C,D,E,F,G]),'immediate-release-opioid',countable) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(9),[A,B,C,D,E,F,G]),'lowest-effective-dose',countable) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(9),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(10),[A,B,C,D,E,F,G]),'expected-severe-pain-duration',countable) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(10),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(11),[A,B,C,D,E,F,G]),prescribe) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(11),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(11),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(11),[A,B,C,D,E,F,G]),for,'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(10),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec01-imp02',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(11),[A,B,C,D,E,F,G]),at,'$guideline_id'(product,'cdc2022-opioid-rec01-imp02',1,ref(9),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,'acute-pain-diagnosis',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,warrant), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain-severity',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'opioid-use',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,warrant), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
