% cdc2022-opioid-rec09-imp18.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec09-imp18',ace_sha256('324d8472cebadb382fccff544bb404346e1a74c7b4a1015fbb09938fb19f7205'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a clinician manages a patient and an other-clinician prescribes a controlled-substance for the patient then the clinician should discuss a safety-concern with the other-clinician.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp18',1,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,manage), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'other-clinician',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'controlled-substance',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,prescribe), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,B).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp18',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp18',1,ref(7),[A,B,C,D,E,F]),'safety-concern',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,manage), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'other-clinician',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'controlled-substance',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,prescribe), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,B).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp18',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp18',1,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,manage), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'other-clinician',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'controlled-substance',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,prescribe), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,B).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp18',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp18',1,ref(8),[A,B,C,D,E,F]),discuss) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,manage), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'other-clinician',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'controlled-substance',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,prescribe), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp18',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp18',1,ref(8),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,manage), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'other-clinician',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'controlled-substance',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,prescribe), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,B).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp18',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp18',1,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp18',1,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,manage), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'other-clinician',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'controlled-substance',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,prescribe), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,B).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp18',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp18',1,ref(8),[A,B,C,D,E,F]),with,D) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,manage), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'other-clinician',countable), guideline_cardinality(actual,D,na,eq,1), guideline_entity(actual,E,'controlled-substance',countable), guideline_cardinality(actual,E,na,eq,1), guideline_event(actual,F,prescribe), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E), guideline_pp(actual,F,for,B).
