% cdc2022-opioid-rec08-imp16.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec08-imp16',ace_sha256('0f8d2d186273d2c1e6c95c8fcf1b5074e0d425c664688846ca5acd7d682dc402'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: Every clinician should provide an opioid-other-drug-overdose-risk-counseling to a patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(2),[A]),'opioid-other-drug-overdose-risk-counseling',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(4),[A]),provide) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(4),[A]),3,'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',1,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every clinician should provide an opioid-alcohol-overdose-risk-counseling to a patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(2),[A]),'opioid-alcohol-overdose-risk-counseling',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(4),[A]),provide) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(4),[A]),3,'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',2,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S3: If a patient has a substance-use-disorder-treatment-need then every clinician should ensure an effective-substance-use-disorder-treatment for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec08-imp16',3,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-treatment-need',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',3,ref(5),[A,B,C,D]),'effective-substance-use-disorder-treatment',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-treatment-need',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',3,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-treatment-need',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',3,ref(6),[A,B,C,D]),ensure) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-treatment-need',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',3,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-treatment-need',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',3,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',3,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-treatment-need',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec08-imp16',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec08-imp16',3,ref(6),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'substance-use-disorder-treatment-need',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
