% cdc2022-opioid-s42-15.pl compiled from ACE by ace_to_pl; regenerate via ckc compile; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/4).
:- discontiguous(guideline_document/4).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
:- multifile(guideline_interval/6).
:- discontiguous(guideline_interval/6).
:- multifile(guideline_recurrence/4).
:- discontiguous(guideline_recurrence/4).
:- multifile(guideline_frequency/5).
:- discontiguous(guideline_frequency/5).
:- multifile(guideline_order/4).
:- discontiguous(guideline_order/4).
:- multifile(guideline_recurrence_window/7).
:- discontiguous(guideline_recurrence_window/7).
:- multifile(guideline_range/3).
:- discontiguous(guideline_range/3).
guideline_schema_version(3).
guideline_document('cdc2022-opioid-s42-15',ace_sha256('9af0b395018f76e2f670d29dd19804d2ca335d3faa7b0e380ccbae7bd26042b2'),ulex(sha256('0b669018d532f506c518a6b0edffa4994f771b930477e7e2b36faf50d2b75d33')),temporal(sha256(d7b0d6c9af49f8d4b3dc12370d6b1cc20e923a69a5ce745ee26a1bc0f21effb6))).
% S1: If a patient has a continuous-opioid-use and the continuous-opioid-use has a duration and the duration includes more than 3 days and the duration includes less than 7 days then every clinician may reduce a daily-opioid-dosage to 50 percent during 2 days for an opioid-withdrawal-symptom-amelioration during an opioid-discontinuation for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(11),[A,B,C,D,E,F,G,H,I,J]),'daily-opioid-dosage',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(11),[A,B,C,D,E,F,G,H,I,J]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(12),[A,B,C,D,E,F,G,H,I,J]),percent,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(12),[A,B,C,D,E,F,G,H,I,J]),na,eq,50) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(13),[A,B,C,D,E,F,G,H,I,J]),day,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(13),[A,B,C,D,E,F,G,H,I,J]),na,eq,2) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(14),[A,B,C,D,E,F,G,H,I,J]),'opioid-withdrawal-symptom-amelioration',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(14),[A,B,C,D,E,F,G,H,I,J]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(15),[A,B,C,D,E,F,G,H,I,J]),'opioid-discontinuation',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(15),[A,B,C,D,E,F,G,H,I,J]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),reduce) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),1,J) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),2,'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(11),[A,B,C,D,E,F,G,H,I,J])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),during,'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(15),[A,B,C,D,E,F,G,H,I,J])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),for,'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(14),[A,B,C,D,E,F,G,H,I,J])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),during,'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(13),[A,B,C,D,E,F,G,H,I,J])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_interval('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),duration,'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(13),[A,B,C,D,E,F,G,H,I,J]),day,none) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-15',1,box(1),[A,B,C,D,E,F,G,H,I,J]),'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(16),[A,B,C,D,E,F,G,H,I,J]),to,'$guideline_id'(product,'cdc2022-opioid-s42-15',1,ref(12),[A,B,C,D,E,F,G,H,I,J])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,duration,countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,day,countable), guideline_cardinality(actual,F,na,greater,3), guideline_event(actual,G,include), guideline_arg(actual,G,1,D), guideline_arg(actual,G,2,F), guideline_event(actual,I,include), guideline_arg(actual,I,1,D), guideline_arg(actual,I,2,H), guideline_entity(actual,H,day,countable), guideline_cardinality(actual,H,na,less,7), guideline_entity(actual,J,clinician,countable), guideline_cardinality(actual,J,na,eq,1).
