% cdc2022-opioid-rec10-imp14.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec10-imp14',ace_sha256('7984d40ea2d686a0f432a795897065590f271bed0a61b50f371d5f2dc2aae378'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: Every opioid-dosage-reduction-decision is an opioid-dosage-management-decision.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',1,ref(2),[A]),'opioid-dosage-management-decision',countable) :- guideline_entity(actual,A,'opioid-dosage-reduction-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'opioid-dosage-reduction-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',1,ref(3),[A]),be) :- guideline_entity(actual,A,'opioid-dosage-reduction-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',1,ref(3),[A]),1,A) :- guideline_entity(actual,A,'opioid-dosage-reduction-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',1,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',1,ref(2),[A])) :- guideline_entity(actual,A,'opioid-dosage-reduction-decision',countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every opioid-dosage-continuation-decision is an opioid-dosage-management-decision.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',2,ref(2),[A]),'opioid-dosage-management-decision',countable) :- guideline_entity(actual,A,'opioid-dosage-continuation-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'opioid-dosage-continuation-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',2,ref(3),[A]),be) :- guideline_entity(actual,A,'opioid-dosage-continuation-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',2,ref(3),[A]),1,A) :- guideline_entity(actual,A,'opioid-dosage-continuation-decision',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',2,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',2,ref(2),[A])) :- guideline_entity(actual,A,'opioid-dosage-continuation-decision',countable), guideline_cardinality(actual,A,na,eq,1).
% S3: Every evidence-based-medication-treatment-offer is an opioid-use-disorder-medication-treatment-action.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',3,ref(2),[A]),'opioid-use-disorder-medication-treatment-action',countable) :- guideline_entity(actual,A,'evidence-based-medication-treatment-offer',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',3,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'evidence-based-medication-treatment-offer',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',3,ref(3),[A]),be) :- guideline_entity(actual,A,'evidence-based-medication-treatment-offer',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',3,ref(3),[A]),1,A) :- guideline_entity(actual,A,'evidence-based-medication-treatment-offer',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',3,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',3,ref(2),[A])) :- guideline_entity(actual,A,'evidence-based-medication-treatment-offer',countable), guideline_cardinality(actual,A,na,eq,1).
% S4: Every patient-referral-for-medication-treatment is an opioid-use-disorder-medication-treatment-action.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',4,ref(2),[A]),'opioid-use-disorder-medication-treatment-action',countable) :- guideline_entity(actual,A,'patient-referral-for-medication-treatment',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',4,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'patient-referral-for-medication-treatment',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',4,ref(3),[A]),be) :- guideline_entity(actual,A,'patient-referral-for-medication-treatment',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',4,ref(3),[A]),1,A) :- guideline_entity(actual,A,'patient-referral-for-medication-treatment',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',4,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',4,ref(2),[A])) :- guideline_entity(actual,A,'patient-referral-for-medication-treatment',countable), guideline_cardinality(actual,A,na,eq,1).
% S5: If a patient has an unexpected-toxicology-result then every clinician should optimize a pain-management-strategy for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp14',5,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',5,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',5,ref(5),[A,B,C,D]),'pain-management-strategy',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',5,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',5,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',5,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',5,ref(6),[A,B,C,D]),optimize) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',5,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',5,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',5,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',5,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',5,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',5,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',5,ref(6),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S6: If a patient has an unexpected-toxicology-result then every clinician should weigh a benefit against a risk during an opioid-dosage-management-decision for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(5),[A,B,C,D]),benefit,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(6),[A,B,C,D]),risk,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(7),[A,B,C,D]),'opioid-dosage-management-decision',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(7),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(8),[A,B,C,D]),weigh) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(8),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(8),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(8),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(8),[A,B,C,D]),during,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(7),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',6,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(8),[A,B,C,D]),against,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',6,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S7: If a patient has an unexpected-toxicology-result then every clinician should increase a follow-up-frequency for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp14',7,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',7,ref(5),[A,B,C,D]),'follow-up-frequency',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',7,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',7,ref(6),[A,B,C,D]),increase) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',7,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',7,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',7,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',7,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',7,ref(6),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S8: If a patient has an unexpected-toxicology-result then every clinician should offer a naloxone-dose to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp14',8,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',8,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',8,ref(5),[A,B,C,D]),'naloxone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',8,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',8,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',8,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',8,ref(6),[A,B,C,D]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',8,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',8,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',8,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',8,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',8,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',8,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',8,ref(6),[A,B,C,D]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S9: If a patient has an unexpected-toxicology-result then every clinician should conduct an opioid-use-disorder-medication-treatment-action for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec10-imp14',9,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',9,ref(5),[A,B,C,D]),'opioid-use-disorder-medication-treatment-action',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',9,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',9,ref(6),[A,B,C,D]),conduct) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',9,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',9,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',9,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec10-imp14',9,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec10-imp14',9,ref(6),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'unexpected-toxicology-result',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
