% cdc2022-opioid-s59-12.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s59-12',ace_sha256(cdd8fbbf7365a3cddfbd2ee26b8ad5912a2ab562d0030aafcbc6afd1160a625b),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: Every naltrexone-initiation-opioid-free-interval should contain at least 7 opioid-free-days and should contain at most 10 opioid-free-days.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(1),[A]),should) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(2),[A]),'opioid-free-day',countable) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(2),[A]),na,geq,7) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(3),[A]),contain) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(3),[A]),1,A) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(2),[A])) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(2),[A]),should) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(4),[A]),contain) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(4),[A]),1,A) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(5),[A])) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(5),[A]),'opioid-free-day',countable) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-12',1,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-12',1,ref(5),[A]),na,leq,10) :- guideline_entity(actual,A,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,A,na,eq,1).
% S2: If a patient does not have a naltrexone-initiation-opioid-free-interval then every clinician should not administer a first-naltrexone-dose to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(2),[A,B]),-) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_operator('$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(2),[A,B]),'$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(3),[A,B]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-s59-12',2,ref(5),[A,B]),'first-naltrexone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-s59-12',2,ref(5),[A,B]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-s59-12',2,ref(6),[A,B]),administer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-s59-12',2,ref(6),[A,B]),1,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-s59-12',2,ref(6),[A,B]),2,'$guideline_id'(product,'cdc2022-opioid-s59-12',2,ref(5),[A,B])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s59-12',2,box(3),[A,B]),'$guideline_id'(product,'cdc2022-opioid-s59-12',2,ref(6),[A,B]),to,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,C,-), guideline_entity(C,D,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(C,D,na,eq,1), guideline_event(C,E,have), guideline_arg(C,E,1,A), guideline_arg(C,E,2,D), guideline_entity(actual,B,clinician,countable), guideline_cardinality(actual,B,na,eq,1).
% S3: If a patient has a naltrexone-initiation-opioid-free-interval then every clinician may administer a first-naltrexone-dose to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s59-12',3,box(1),[A,B,C,D]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-12',3,ref(5),[A,B,C,D]),'first-naltrexone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-12',3,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s59-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-12',3,ref(6),[A,B,C,D]),administer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-12',3,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-12',3,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s59-12',3,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s59-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-12',3,ref(6),[A,B,C,D]),to,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'naltrexone-initiation-opioid-free-interval',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
