% cdc2022-opioid-rec05-imp04.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec05-imp04',ace_sha256('92caebd100e12f6c51798067887134caa12f6c49924d7b4171218a19607c09fe'),ulex(sha256('0e8a9a04fd387b8eab12faf03224671330b94c03dff5f0bf39f23a8d14af88bd'))).
% S1: If a continued-opioid-benefit matches a continued-opioid-risk then a shared-decision-making is important with a patient.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(4),[A,B,C]),'shared-decision-making',countable) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(4),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(5),[A,B,C]),patient,countable) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(5),[A,B,C]),na,eq,1) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_property(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(6),[A,B,C]),important,pos) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(7),[A,B,C]),be) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(7),[A,B,C]),1,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(4),[A,B,C])) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(7),[A,B,C]),2,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(6),[A,B,C])) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
guideline_pp(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(7),[A,B,C]),with,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',1,ref(5),[A,B,C])) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continued-opioid-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,match), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B).
% S2: If a continued-opioid-benefit is unclear and a continued-opioid-risk is unclear then a shared-decision-making is important with a patient.
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(7),[A,B,C,D,E,F]),'shared-decision-making',countable) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_entity(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(8),[A,B,C,D,E,F]),patient,countable) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_cardinality(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(8),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_property(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(9),[A,B,C,D,E,F]),important,pos) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_event(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(10),[A,B,C,D,E,F]),be) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(10),[A,B,C,D,E,F]),1,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_arg(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
guideline_pp(actual,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(10),[A,B,C,D,E,F]),with,'$guideline_id'(product,'cdc2022-opioid-rec05-imp04',2,ref(8),[A,B,C,D,E,F])) :- guideline_entity(actual,A,'continued-opioid-benefit',countable), guideline_cardinality(actual,A,na,eq,1), guideline_property(actual,B,unclear,pos), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'continued-opioid-risk',countable), guideline_cardinality(actual,D,na,eq,1), guideline_property(actual,E,unclear,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,D), guideline_arg(actual,F,2,E).
