% cdc2022-opioid-rec09-imp17.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec09-imp17',ace_sha256('6d4e3bb53022f71aec3216d625e35334f87bf5dc787e625e2cab96963139fa46'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a patient has an overdose-risk from a total-daily-dosage then every clinician should discuss the overdose-risk with the patient and should make a taper-benefit-over-risk-determination with the patient and should offer a naloxone-dose to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(6),[A,B,C,D,E]),discuss) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(6),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(6),[A,B,C,D,E]),2,B) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(6),[A,B,C,D,E]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(2),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(7),[A,B,C,D,E]),'taper-benefit-over-risk-determination',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(7),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(8),[A,B,C,D,E]),make) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(8),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(8),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(7),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(2),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(8),[A,B,C,D,E]),with,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(3),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(9),[A,B,C,D,E]),'naloxone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(9),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(10),[A,B,C,D,E]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(10),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(10),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(9),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp17',1,box(3),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp17',1,ref(10),[A,B,C,D,E]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'overdose-risk',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'total-daily-dosage',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,from,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
