% cdc2022-opioid-s22-08.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s22-08',ace_sha256('89011b7743a03b22fcca6907f18a6a6d7d6046e5f622a3fd13e0c6a7e7034146'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a patient is an opioid-naive-patient and has an acute-pain and an opioid-use-minimizing-strategy is possible then every clinician should implement the opioid-use-minimizing-strategy for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s22-08',1,box(1),[A,B,C,D,E,F,G,H,I]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-naive-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s22-08',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',1,ref(10),[A,B,C,D,E,F,G,H,I]),implement) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-naive-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s22-08',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',1,ref(10),[A,B,C,D,E,F,G,H,I]),1,I) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-naive-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s22-08',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',1,ref(10),[A,B,C,D,E,F,G,H,I]),2,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-naive-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s22-08',1,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',1,ref(10),[A,B,C,D,E,F,G,H,I]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-naive-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
% S2: If a patient is an opioid-tolerant-patient and has an acute-pain and an opioid-use-minimizing-strategy is possible then every clinician should implement the opioid-use-minimizing-strategy for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s22-08',2,box(1),[A,B,C,D,E,F,G,H,I]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-tolerant-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s22-08',2,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',2,ref(10),[A,B,C,D,E,F,G,H,I]),implement) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-tolerant-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s22-08',2,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',2,ref(10),[A,B,C,D,E,F,G,H,I]),1,I) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-tolerant-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s22-08',2,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',2,ref(10),[A,B,C,D,E,F,G,H,I]),2,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-tolerant-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s22-08',2,box(1),[A,B,C,D,E,F,G,H,I]),'$guideline_id'(product,'cdc2022-opioid-s22-08',2,ref(10),[A,B,C,D,E,F,G,H,I]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-tolerant-patient',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,be), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'acute-pain',countable), guideline_cardinality(actual,D,na,eq,1), guideline_event(actual,E,have), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,D), guideline_entity(actual,F,'opioid-use-minimizing-strategy',countable), guideline_cardinality(actual,F,na,eq,1), guideline_property(actual,G,possible,pos), guideline_event(actual,H,be), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_entity(actual,I,clinician,countable), guideline_cardinality(actual,I,na,eq,1).
