% cdc2022-opioid-s42-16.pl compiled from ACE by ace_to_pl; regenerate via ckc compile; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/4).
:- discontiguous(guideline_document/4).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
:- multifile(guideline_interval/6).
:- discontiguous(guideline_interval/6).
:- multifile(guideline_recurrence/4).
:- discontiguous(guideline_recurrence/4).
:- multifile(guideline_frequency/5).
:- discontiguous(guideline_frequency/5).
:- multifile(guideline_order/4).
:- discontiguous(guideline_order/4).
:- multifile(guideline_recurrence_window/7).
:- discontiguous(guideline_recurrence_window/7).
:- multifile(guideline_range/3).
:- discontiguous(guideline_range/3).
guideline_schema_version(3).
guideline_document('cdc2022-opioid-s42-16',ace_sha256('9ab92f5bd4bc4dfc3b9251aeb7f3a53ce1e164c0e8ea44fedc62758b3299253f'),ulex(sha256(be24cf56c59049d3c31fba641013faa22821ecda0669443a1fc4a49979ef57ae)),temporal(sha256('29a90281976bb48dfa32d9ef80651076896404c524c9bf1d7a55b06c1880be2a'))).
% S1: If a patient has a continuous-opioid-use that lasts for at least 1 week for less than 1 month then every clinician may use a gradual-taper for the patient and may reduce a daily-opioid-dosage by 20 percent at an interval of 2 days for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(1),[A,B,C,D,E,F,G]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(8),[A,B,C,D,E,F,G]),'gradual-taper',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(8),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(9),[A,B,C,D,E,F,G]),use) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(9),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(9),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(8),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(1),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(9),[A,B,C,D,E,F,G]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(10),[A,B,C,D,E,F,G]),'daily-opioid-dosage',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(10),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(11),[A,B,C,D,E,F,G]),percent,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(11),[A,B,C,D,E,F,G]),na,eq,20) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(12),[A,B,C,D,E,F,G]),interval,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(12),[A,B,C,D,E,F,G]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(13),[A,B,C,D,E,F,G]),day,countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(13),[A,B,C,D,E,F,G]),na,eq,2) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(14),[A,B,C,D,E,F,G]),reduce) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(14),[A,B,C,D,E,F,G]),1,G) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(14),[A,B,C,D,E,F,G]),2,'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(10),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(14),[A,B,C,D,E,F,G]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(14),[A,B,C,D,E,F,G]),at,'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(12),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_recurrence('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(14),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(13),[A,B,C,D,E,F,G]),day) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s42-16',1,box(2),[A,B,C,D,E,F,G]),'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(14),[A,B,C,D,E,F,G]),by,'$guideline_id'(product,'cdc2022-opioid-s42-16',1,ref(11),[A,B,C,D,E,F,G])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'continuous-opioid-use',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,week,countable), guideline_cardinality(actual,C,na,geq,1), guideline_pp(actual,E,for,C), guideline_interval(actual,E,duration,C,week,none), guideline_pp(actual,E,for,D), guideline_interval(actual,E,duration,D,month,none), guideline_event(actual,E,last), guideline_arg(actual,E,1,B), guideline_entity(actual,D,month,countable), guideline_cardinality(actual,D,na,less,1), guideline_event(actual,F,have), guideline_arg(actual,F,1,A), guideline_arg(actual,F,2,B), guideline_entity(actual,G,clinician,countable), guideline_cardinality(actual,G,na,eq,1).
