% cdc2022-opioid-rec02-imp26.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec02-imp26',ace_sha256(f24cecd5b8a2a58372bf2aff0343173bc1adb8fd585d22a8758e73c67353ebd3),ulex(sha256('9d39595833bb1358c343511806091b34e2442561f073b432f531f68ac385a15e'))).
% S1: Every clinician should explain an expected-opioid-benefit with a patient before an opioid-initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(2),[A]),'expected-opioid-benefit',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(4),[A]),'opioid-initiation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',1,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every clinician should explain an expected-opioid-benefit with a patient before an opioid-continuation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(2),[A]),'expected-opioid-benefit',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(4),[A]),'opioid-continuation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',2,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S3: Every clinician should explain a common-opioid-risk with a patient before an opioid-initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(2),[A]),'common-opioid-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(4),[A]),'opioid-initiation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',3,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S4: Every clinician should explain a common-opioid-risk with a patient before an opioid-continuation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(2),[A]),'common-opioid-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(4),[A]),'opioid-continuation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',4,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S5: Every clinician should explain a serious-opioid-risk with a patient before an opioid-initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(2),[A]),'serious-opioid-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(4),[A]),'opioid-initiation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',5,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S6: Every clinician should explain a serious-opioid-risk with a patient before an opioid-continuation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(2),[A]),'serious-opioid-risk',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(4),[A]),'opioid-continuation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',6,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S7: Every clinician should explain an opioid-alternative with a patient before an opioid-initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(2),[A]),'opioid-alternative',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(4),[A]),'opioid-initiation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',7,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S8: Every clinician should explain an opioid-alternative with a patient before an opioid-continuation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(2),[A]),'opioid-alternative',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(4),[A]),'opioid-continuation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(5),[A]),explain) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',8,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S9: Every clinician should involve a patient in an opioid-start-decision.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(2),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(3),[A]),'opioid-start-decision',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(4),[A]),involve) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp26',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(4),[A]),in,'$guideline_id'(product,'cdc2022-opioid-rec02-imp26',9,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
