% cdc2022-opioid-rec09-imp04.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec09-imp04',ace_sha256('5dfb6ede0be802dd213567634900f5ea5282ca584177406aad10a25953987b2b'),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a clinician considers a patient under a PDMP-recommendation and the PDMP-recommendation is feasible then the clinician should apply the PDMP-recommendation to the patient and should minimize a bias.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(7),[A,B,C,D,E,F]),apply) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(7),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(7),[A,B,C,D,E,F]),2,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(7),[A,B,C,D,E,F]),3,B) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(8),[A,B,C,D,E,F]),bias,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(8),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(9),[A,B,C,D,E,F]),minimize) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(9),[A,B,C,D,E,F]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec09-imp04',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(9),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-rec09-imp04',1,ref(8),[A,B,C,D,E,F])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,patient,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'PDMP-recommendation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,consider), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,under,C), guideline_property(actual,E,feasible,pos), guideline_event(actual,F,be), guideline_arg(actual,F,1,C), guideline_arg(actual,F,2,E).
