% cdc2022-opioid-rec05-imp22.pl compiled from ACE by ace_to_pl; regenerate via ckc compile; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/4).
:- discontiguous(guideline_document/4).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
:- multifile(guideline_interval/6).
:- discontiguous(guideline_interval/6).
:- multifile(guideline_recurrence/4).
:- discontiguous(guideline_recurrence/4).
:- multifile(guideline_frequency/5).
:- discontiguous(guideline_frequency/5).
:- multifile(guideline_order/4).
:- discontiguous(guideline_order/4).
:- multifile(guideline_recurrence_window/7).
:- discontiguous(guideline_recurrence_window/7).
:- multifile(guideline_range/3).
:- discontiguous(guideline_range/3).
guideline_schema_version(3).
guideline_document('cdc2022-opioid-rec05-imp22',ace_sha256('8c6c811501dd83b324aac4bc3639adb56e52f7b07802e29d9b760375e455cd5c'),ulex(sha256(be24cf56c59049d3c31fba641013faa22821ecda0669443a1fc4a49979ef57ae)),temporal(sha256('29a90281976bb48dfa32d9ef80651076896404c524c9bf1d7a55b06c1880be2a'))).
% S1: If a patient cannot taper an opioid and continues a high-dosage-opioid then every clinician should monitor the patient and should mitigate an overdose-risk with an overdose-education and should offer a naloxone-dose.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(3),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(7),[A,B,C,D]),monitor) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(7),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(7),[A,B,C,D]),2,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(8),[A,B,C,D]),'overdose-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(8),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(9),[A,B,C,D]),'overdose-education',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(9),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(10),[A,B,C,D]),mitigate) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(10),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(10),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(8),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(10),[A,B,C,D]),with,'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(9),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(5),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(11),[A,B,C,D]),'naloxone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(11),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(12),[A,B,C,D]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(12),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',1,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(12),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',1,ref(11),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-dosage-opioid',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S2: If a patient cannot taper an opioid and continues a high-risk-opioid-regimen then every clinician should monitor the patient and should mitigate an overdose-risk with an overdose-education and should offer a naloxone-dose.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(3),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(7),[A,B,C,D]),monitor) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(7),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(3),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(7),[A,B,C,D]),2,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(8),[A,B,C,D]),'overdose-risk',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(8),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(9),[A,B,C,D]),'overdose-education',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(9),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(10),[A,B,C,D]),mitigate) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(10),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(10),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(8),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(4),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(10),[A,B,C,D]),with,'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(9),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(5),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(11),[A,B,C,D]),'naloxone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(11),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(12),[A,B,C,D]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(12),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec05-imp22',2,box(5),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(12),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-rec05-imp22',2,ref(11),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,E,-), guideline_operator(E,F,can), guideline_entity(F,G,opioid,countable), guideline_cardinality(F,G,na,eq,1), guideline_event(F,H,taper), guideline_arg(F,H,1,A), guideline_arg(F,H,2,G), guideline_entity(actual,B,'high-risk-opioid-regimen',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,continue), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
