% cdc2022-opioid-s58-12.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s58-12',ace_sha256(cefe7d643c7ecb3fdea232203ef090c38f5c99deee3cac68be881af3bd365882),ulex(sha256('4a882a1996ea910df0fbf91fea897c0805e67d48f9e1ce2fcdbbbd9250c193ae'))).
% S1: If a patient has an opioid-use-disorder then every clinician may offer an opioid-use-disorder-counseling to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s58-12',1,box(1),[A,B,C,D]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s58-12',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',1,ref(5),[A,B,C,D]),'opioid-use-disorder-counseling',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s58-12',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',1,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s58-12',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',1,ref(6),[A,B,C,D]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',1,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',1,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s58-12',1,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',1,ref(6),[A,B,C,D]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S2: If a clinician offers an opioid-use-disorder-counseling to a patient then the clinician should not replace an evidence-based-medication-treatment for the patient with an opioid-use-disorder-counseling.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(1),[A,B,C,D]),-) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_operator('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(1),[A,B,C,D]),'$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(5),[A,B,C,D]),'evidence-based-medication-treatment',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(6),[A,B,C,D]),'opioid-use-disorder-counseling',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(7),[A,B,C,D]),replace) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(7),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(7),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(7),[A,B,C,D]),with,'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s58-12',2,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',2,ref(7),[A,B,C,D]),for,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder-counseling',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
% S3: If a patient has an opioid-use-disorder then every clinician may offer a mutual-help-group-referral to the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s58-12',3,box(1),[A,B,C,D]),may) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s58-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',3,ref(5),[A,B,C,D]),'mutual-help-group-referral',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s58-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',3,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s58-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',3,ref(6),[A,B,C,D]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',3,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',3,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s58-12',3,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',3,ref(6),[A,B,C,D]),3,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'opioid-use-disorder',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S4: If a clinician offers a mutual-help-group-referral to a patient then the clinician should not replace an evidence-based-medication-treatment for the patient with a mutual-help-group-referral.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(1),[A,B,C,D]),-) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_operator('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(1),[A,B,C,D]),'$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(5),[A,B,C,D]),'evidence-based-medication-treatment',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(6),[A,B,C,D]),'mutual-help-group-referral',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(7),[A,B,C,D]),replace) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(7),[A,B,C,D]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(7),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(7),[A,B,C,D]),with,'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s58-12',4,box(2),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s58-12',4,ref(7),[A,B,C,D]),for,C) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'mutual-help-group-referral',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,patient,countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,offer), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_arg(actual,D,3,C).
