% cdc2022-opioid-s25-08.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s25-08',ace_sha256('1576c07f1eae7ab610db4a3a38dc4dadf319d44939898340b744dc4a46b78a23'),ulex(sha256('06c1c26d6b6abe1436b8c94a276937ad072806062117417de2ab8086fdf9a3e9'))).
% S1: If a clinician does not conduct a patient-specific-medication-assessment then the clinician should not use a medication.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(2),[A]),-) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'patient-specific-medication-assessment',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,conduct), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_operator('$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(2),[A]),'$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(3),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'patient-specific-medication-assessment',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,conduct), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',1,ref(4),[A]),medication,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'patient-specific-medication-assessment',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,conduct), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',1,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'patient-specific-medication-assessment',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,conduct), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',1,ref(5),[A]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'patient-specific-medication-assessment',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,conduct), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',1,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'patient-specific-medication-assessment',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,conduct), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s25-08',1,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',1,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s25-08',1,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'patient-specific-medication-assessment',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,conduct), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
% S2: If a clinician does not make an expected-benefit-risk-determination then the clinician should not use a medication.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(2),[A]),-) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'expected-benefit-risk-determination',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,make), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_operator('$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(2),[A]),'$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(3),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'expected-benefit-risk-determination',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,make), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',2,ref(4),[A]),medication,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'expected-benefit-risk-determination',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,make), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',2,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'expected-benefit-risk-determination',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,make), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',2,ref(5),[A]),use) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'expected-benefit-risk-determination',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,make), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',2,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'expected-benefit-risk-determination',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,make), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s25-08',2,box(3),[A]),'$guideline_id'(product,'cdc2022-opioid-s25-08',2,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s25-08',2,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1), guideline_operator(actual,B,-), guideline_entity(B,C,'expected-benefit-risk-determination',countable), guideline_cardinality(B,C,na,eq,1), guideline_event(B,D,make), guideline_arg(B,D,1,A), guideline_arg(B,D,2,C).
