% cdc2022-opioid-rec06-imp07.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec06-imp07',ace_sha256(bffee2114d1674f7267fa8eef62cf7415bbf95ff23f520a21f16b5f1441ec772),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a patient receives an opioid for an acute-pain and continues the opioid and an acute-opioid-evaluation-schedule has an evaluation-interval and the evaluation-interval includes at most 2 weeks then every clinician should use the acute-opioid-evaluation-schedule for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec06-imp07',1,box(1),[A,B,C,D,E,F,G,H,I,J,K]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'acute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,continue), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_entity(actual,F,'acute-opioid-evaluation-schedule',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'evaluation-interval',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,have), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_event(actual,J,include), guideline_arg(actual,J,1,G), guideline_arg(actual,J,2,I), guideline_entity(actual,I,week,countable), guideline_cardinality(actual,I,na,leq,2), guideline_entity(actual,K,clinician,countable), guideline_cardinality(actual,K,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec06-imp07',1,box(1),[A,B,C,D,E,F,G,H,I,J,K]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp07',1,ref(12),[A,B,C,D,E,F,G,H,I,J,K]),use) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'acute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,continue), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_entity(actual,F,'acute-opioid-evaluation-schedule',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'evaluation-interval',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,have), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_event(actual,J,include), guideline_arg(actual,J,1,G), guideline_arg(actual,J,2,I), guideline_entity(actual,I,week,countable), guideline_cardinality(actual,I,na,leq,2), guideline_entity(actual,K,clinician,countable), guideline_cardinality(actual,K,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec06-imp07',1,box(1),[A,B,C,D,E,F,G,H,I,J,K]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp07',1,ref(12),[A,B,C,D,E,F,G,H,I,J,K]),1,K) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'acute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,continue), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_entity(actual,F,'acute-opioid-evaluation-schedule',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'evaluation-interval',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,have), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_event(actual,J,include), guideline_arg(actual,J,1,G), guideline_arg(actual,J,2,I), guideline_entity(actual,I,week,countable), guideline_cardinality(actual,I,na,leq,2), guideline_entity(actual,K,clinician,countable), guideline_cardinality(actual,K,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec06-imp07',1,box(1),[A,B,C,D,E,F,G,H,I,J,K]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp07',1,ref(12),[A,B,C,D,E,F,G,H,I,J,K]),2,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'acute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,continue), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_entity(actual,F,'acute-opioid-evaluation-schedule',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'evaluation-interval',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,have), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_event(actual,J,include), guideline_arg(actual,J,1,G), guideline_arg(actual,J,2,I), guideline_entity(actual,I,week,countable), guideline_cardinality(actual,I,na,leq,2), guideline_entity(actual,K,clinician,countable), guideline_cardinality(actual,K,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec06-imp07',1,box(1),[A,B,C,D,E,F,G,H,I,J,K]),'$guideline_id'(product,'cdc2022-opioid-rec06-imp07',1,ref(12),[A,B,C,D,E,F,G,H,I,J,K]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,opioid,countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'acute-pain',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,receive), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,for,C), guideline_event(actual,E,continue), guideline_arg(actual,E,1,A), guideline_arg(actual,E,2,B), guideline_entity(actual,F,'acute-opioid-evaluation-schedule',countable), guideline_cardinality(actual,F,na,eq,1), guideline_entity(actual,G,'evaluation-interval',countable), guideline_cardinality(actual,G,na,eq,1), guideline_event(actual,H,have), guideline_arg(actual,H,1,F), guideline_arg(actual,H,2,G), guideline_event(actual,J,include), guideline_arg(actual,J,1,G), guideline_arg(actual,J,2,I), guideline_entity(actual,I,week,countable), guideline_cardinality(actual,I,na,leq,2), guideline_entity(actual,K,clinician,countable), guideline_cardinality(actual,K,na,eq,1).
