% cdc2022-opioid-s8-06.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s8-06',ace_sha256('1696ec4924b386ca2073d1255e2ceee1bbf2a51d1e741f078fc2d5924f4470d5'),ulex(sha256('2a4a3e829c919b3dd3b20356e7a69585cfb305c3c57dfb531e3f2c1eb97637b6'))).
% S1: Every clinician should evaluate a risk for an opioid-related-harm before an opioid-initiation.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(2),[A]),risk,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(3),[A]),'opioid-related-harm',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(4),[A]),'opioid-initiation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(5),[A]),evaluate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(5),[A]),before,'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(5),[A]),for,'$guideline_id'(product,'cdc2022-opioid-s8-06',1,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every clinician should evaluate a risk for an opioid-related-harm during a periodic-continuation-review.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(2),[A]),risk,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(3),[A]),'opioid-related-harm',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(4),[A]),'periodic-continuation-review',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(5),[A]),evaluate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(5),[A]),during,'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(5),[A]),for,'$guideline_id'(product,'cdc2022-opioid-s8-06',2,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S3: Every clinician should discuss a risk for an opioid-related-harm with a patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(2),[A]),risk,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(3),[A]),'opioid-related-harm',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(4),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(5),[A]),discuss) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(5),[A]),for,'$guideline_id'(product,'cdc2022-opioid-s8-06',3,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S4: Every clinician should incorporate a risk-mitigation-strategy in a management-plan with a patient and should offer a naloxone-dose.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(2),[A]),'risk-mitigation-strategy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(3),[A]),'management-plan',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(4),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(5),[A]),incorporate) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(5),[A]),in,'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(2),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(6),[A]),'naloxone-dose',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(6),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(7),[A]),offer) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(7),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',4,box(2),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(7),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s8-06',4,ref(6),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S5: Every clinician should review a potential-prescribed-medication-interaction with a patient during an opioid-therapy.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(2),[A]),'potential-prescribed-medication-interaction',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(4),[A]),'opioid-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(5),[A]),review) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(5),[A]),during,'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-s8-06',5,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S6: Every clinician should review a potential-used-substance-interaction with a patient during an opioid-therapy.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(2),[A]),'potential-used-substance-interaction',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(3),[A]),patient,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(4),[A]),'opioid-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(4),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(5),[A]),review) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(5),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(5),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(5),[A]),during,'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(4),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s8-06',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(5),[A]),with,'$guideline_id'(product,'cdc2022-opioid-s8-06',6,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
