% cdc2022-opioid-rec02-imp02.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-rec02-imp02',ace_sha256('49df2808a2032cf6f1d71ea65e67964407f79cafff47d5df42a0fecfdd44db5b'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: Every clinician should recommend an exercise-therapy for a back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(2),[A]),'exercise-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(3),[A]),'back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',1,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every clinician should recommend an exercise-therapy for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(2),[A]),'exercise-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',2,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S3: Every clinician should recommend an exercise-therapy for a hip-osteoarthritis.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(2),[A]),'exercise-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(3),[A]),'hip-osteoarthritis',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',3,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S4: Every clinician should recommend an exercise-therapy for a knee-osteoarthritis.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(2),[A]),'exercise-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(3),[A]),'knee-osteoarthritis',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',4,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',4,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S5: Every clinician should recommend a weight-loss for a knee-osteoarthritis.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(2),[A]),'weight-loss',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(3),[A]),'knee-osteoarthritis',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',5,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',5,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S6: Every clinician should recommend a manual-therapy for a hip-osteoarthritis.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(2),[A]),'manual-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(3),[A]),'hip-osteoarthritis',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',6,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',6,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S7: Every clinician should recommend a psychological-therapy for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(2),[A]),'psychological-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',7,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',7,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S8: Every clinician should recommend a spinal-manipulation for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(2),[A]),'spinal-manipulation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',8,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',8,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S9: Every clinician should recommend a low-level-laser-therapy for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(2),[A]),'low-level-laser-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',9,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',9,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S10: Every clinician should recommend a massage for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(2),[A]),massage,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',10,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',10,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S11: Every clinician should recommend a mindfulness-based-stress-reduction for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(2),[A]),'mindfulness-based-stress-reduction',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',11,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',11,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S12: Every clinician should recommend a yoga for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(2),[A]),yoga,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',12,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',12,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S13: Every clinician should recommend an acupuncture for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(2),[A]),acupuncture,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',13,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',13,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S14: Every clinician should recommend a multidisciplinary-rehabilitation for a low-back-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(2),[A]),'multidisciplinary-rehabilitation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(3),[A]),'low-back-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',14,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',14,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S15: Every clinician should recommend a mind-body-practice for a neck-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(2),[A]),'mind-body-practice',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(3),[A]),'neck-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',15,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',15,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S16: Every clinician should recommend a massage for a neck-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(2),[A]),massage,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(3),[A]),'neck-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',16,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',16,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S17: Every clinician should recommend an acupuncture for a neck-pain.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(2),[A]),acupuncture,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(3),[A]),'neck-pain',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',17,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',17,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S18: Every clinician should recommend a cognitive-behavioral-therapy for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(2),[A]),'cognitive-behavioral-therapy',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',18,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',18,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S19: Every clinician should recommend a myofascial-release-massage for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(2),[A]),'myofascial-release-massage',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',19,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',19,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S20: Every clinician should recommend a mindfulness-practice for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(2),[A]),'mindfulness-practice',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',20,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',20,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S21: Every clinician should recommend a tai-chi for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(2),[A]),'tai-chi',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',21,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',21,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S22: Every clinician should recommend a qigong for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(2),[A]),qigong,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',22,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',22,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S23: Every clinician should recommend an acupuncture for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(2),[A]),acupuncture,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',23,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',23,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S24: Every clinician should recommend a multidisciplinary-rehabilitation for a fibromyalgia.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(2),[A]),'multidisciplinary-rehabilitation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(3),[A]),fibromyalgia,countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',24,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',24,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
% S25: Every clinician should recommend a spinal-manipulation for a tension-headache.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),should) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(2),[A]),'spinal-manipulation',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(3),[A]),'tension-headache',countable) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(4),[A]),recommend) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(4),[A]),1,A) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(4),[A]),2,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(2),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-rec02-imp02',25,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-rec02-imp02',25,ref(3),[A])) :- guideline_entity(actual,A,clinician,countable), guideline_cardinality(actual,A,na,eq,1).
