% cdc2022-opioid-s34-10.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s34-10',ace_sha256(d5de4060ed14d558dcfb670883ffe081cd40f080682e88e04813d129c3139f6a),ulex(sha256('06c1c26d6b6abe1436b8c94a276937ad072806062117417de2ab8086fdf9a3e9'))).
% S1: If a patient has a combined-opioid-dosage and the combined-opioid-dosage includes at least 50 MME-units-per-day then every clinician should increase a follow-up-frequency and should offer a naloxone-dose to the patient and should provide an opioid-overdose-education to the patient and should provide an opioid-overdose-education to a patient-household-member.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(1),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(7),[A,B,C,D,E,F]),'follow-up-frequency',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(7),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(8),[A,B,C,D,E,F]),increase) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(8),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(1),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(8),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(7),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(2),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(9),[A,B,C,D,E,F]),'naloxone-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(9),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(10),[A,B,C,D,E,F]),offer) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(10),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(10),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(9),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(2),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(10),[A,B,C,D,E,F]),to,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(3),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(11),[A,B,C,D,E,F]),'opioid-overdose-education',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(11),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(12),[A,B,C,D,E,F]),provide) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(12),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(12),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(11),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(3),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(12),[A,B,C,D,E,F]),to,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(13),[A,B,C,D,E,F]),'opioid-overdose-education',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(13),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(14),[A,B,C,D,E,F]),'patient-household-member',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(14),[A,B,C,D,E,F]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(15),[A,B,C,D,E,F]),provide) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(15),[A,B,C,D,E,F]),1,F) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(15),[A,B,C,D,E,F]),2,'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(13),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s34-10',1,box(4),[A,B,C,D,E,F]),'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(15),[A,B,C,D,E,F]),to,'$guideline_id'(product,'cdc2022-opioid-s34-10',1,ref(14),[A,B,C,D,E,F])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'combined-opioid-dosage',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'MME-unit-per-day',countable), guideline_cardinality(actual,D,na,geq,50), guideline_event(actual,E,include), guideline_arg(actual,E,1,B), guideline_arg(actual,E,2,D), guideline_entity(actual,F,clinician,countable), guideline_cardinality(actual,F,na,eq,1).
