% cdc2022-opioid-s38-11.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s38-11',ace_sha256('7e0915b505f740afc30d7d965295183e35c0c90e761c8093cdfc287bf6469d9b'),ulex(sha256(ef57ba7180864095bab88b95f11ddb1a2c858593eba715dbfbe874db09506c5b))).
% S1: Every primary-care-clinician should collaborate with a mental-health-specialist for an optimized-nonopioid-pain-management.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),should) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(2),[A]),'mental-health-specialist',countable) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(3),[A]),'optimized-nonopioid-pain-management',countable) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(4),[A]),collaborate) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(4),[A]),1,A) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(3),[A])) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',1,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(4),[A]),with,'$guideline_id'(product,'cdc2022-opioid-s38-11',1,ref(2),[A])) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
% S2: Every primary-care-clinician should collaborate with a specialty-clinician for an optimized-nonopioid-pain-management.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),should) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(2),[A]),'specialty-clinician',countable) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(2),[A]),na,eq,1) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(3),[A]),'optimized-nonopioid-pain-management',countable) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(3),[A]),na,eq,1) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(4),[A]),collaborate) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(4),[A]),1,A) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(4),[A]),for,'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(3),[A])) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',2,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(4),[A]),with,'$guideline_id'(product,'cdc2022-opioid-s38-11',2,ref(2),[A])) :- guideline_entity(actual,A,'primary-care-clinician',countable), guideline_cardinality(actual,A,na,eq,1).
% S3: If a patient has a taper-related-anxiety then every primary-care-clinician should collaborate with a mental-health-specialist for a patient-psychosocial-support.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(5),[A,B,C,D]),'mental-health-specialist',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(6),[A,B,C,D]),'patient-psychosocial-support',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(7),[A,B,C,D]),collaborate) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(7),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(7),[A,B,C,D]),for,'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',3,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(7),[A,B,C,D]),with,'$guideline_id'(product,'cdc2022-opioid-s38-11',3,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
% S4: If a patient has a taper-related-anxiety then every primary-care-clinician should collaborate with a specialty-clinician for a patient-psychosocial-support.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(5),[A,B,C,D]),'specialty-clinician',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(6),[A,B,C,D]),'patient-psychosocial-support',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(6),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(7),[A,B,C,D]),collaborate) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(7),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(7),[A,B,C,D]),for,'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(6),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s38-11',4,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(7),[A,B,C,D]),with,'$guideline_id'(product,'cdc2022-opioid-s38-11',4,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'taper-related-anxiety',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,'primary-care-clinician',countable), guideline_cardinality(actual,D,na,eq,1).
