% cdc2022-opioid-s59-06.pl compiled from ACE by ace_to_pl; regenerate via tools/goal.py; do not edit.
:- multifile(guideline_schema_version/1).
:- discontiguous(guideline_schema_version/1).
:- multifile(guideline_document/3).
:- discontiguous(guideline_document/3).
:- multifile(guideline_entity/4).
:- discontiguous(guideline_entity/4).
:- multifile(guideline_cardinality/5).
:- discontiguous(guideline_cardinality/5).
:- multifile(guideline_event/3).
:- discontiguous(guideline_event/3).
:- multifile(guideline_arg/4).
:- discontiguous(guideline_arg/4).
:- multifile(guideline_pp/4).
:- discontiguous(guideline_pp/4).
:- multifile(guideline_property/4).
:- discontiguous(guideline_property/4).
:- multifile(guideline_operator/3).
:- discontiguous(guideline_operator/3).
guideline_schema_version(1).
guideline_document('cdc2022-opioid-s59-06',ace_sha256('006cc8f8cd55ff4f94d0032e29b071e2e98985d48f4a8b211a140c9cbbff1e40'),ulex(sha256('4c55bed7525c11e80d870254a4f876c23b6aa3c2a077242833ec32997784b01c'))).
% S1: If a patient has an objective-opioid-withdrawal-sign then every clinician should conduct a standard-buprenorphine-initiation for the patient.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s59-06',1,box(1),[A,B,C,D]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'objective-opioid-withdrawal-sign',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-06',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-06',1,ref(5),[A,B,C,D]),'standard-buprenorphine-initiation',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'objective-opioid-withdrawal-sign',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-06',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-06',1,ref(5),[A,B,C,D]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'objective-opioid-withdrawal-sign',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s59-06',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-06',1,ref(6),[A,B,C,D]),conduct) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'objective-opioid-withdrawal-sign',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-06',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-06',1,ref(6),[A,B,C,D]),1,D) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'objective-opioid-withdrawal-sign',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-06',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-06',1,ref(6),[A,B,C,D]),2,'$guideline_id'(product,'cdc2022-opioid-s59-06',1,ref(5),[A,B,C,D])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'objective-opioid-withdrawal-sign',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s59-06',1,box(1),[A,B,C,D]),'$guideline_id'(product,'cdc2022-opioid-s59-06',1,ref(6),[A,B,C,D]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'objective-opioid-withdrawal-sign',countable), guideline_cardinality(actual,B,na,eq,1), guideline_event(actual,C,have), guideline_arg(actual,C,1,A), guideline_arg(actual,C,2,B), guideline_entity(actual,D,clinician,countable), guideline_cardinality(actual,D,na,eq,1).
% S2: If a patient has an uncontrolled-opioid-withdrawal-symptom during a standard-buprenorphine-initiation then every clinician should increase a buprenorphine-dose for the patient under a clinical-supervision after a standard-buprenorphine-titration-interval.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),should) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(6),[A,B,C,D,E]),'buprenorphine-dose',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(6),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(7),[A,B,C,D,E]),'clinical-supervision',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(7),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(8),[A,B,C,D,E]),'standard-buprenorphine-titration-interval',countable) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(8),[A,B,C,D,E]),na,eq,1) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(9),[A,B,C,D,E]),increase) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(9),[A,B,C,D,E]),1,E) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(9),[A,B,C,D,E]),2,'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(6),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(9),[A,B,C,D,E]),after,'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(8),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(9),[A,B,C,D,E]),under,'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(7),[A,B,C,D,E])) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
guideline_pp('$guideline_id'(context,'cdc2022-opioid-s59-06',2,box(1),[A,B,C,D,E]),'$guideline_id'(product,'cdc2022-opioid-s59-06',2,ref(9),[A,B,C,D,E]),for,A) :- guideline_entity(actual,A,patient,countable), guideline_cardinality(actual,A,na,eq,1), guideline_entity(actual,B,'uncontrolled-opioid-withdrawal-symptom',countable), guideline_cardinality(actual,B,na,eq,1), guideline_entity(actual,C,'standard-buprenorphine-initiation',countable), guideline_cardinality(actual,C,na,eq,1), guideline_event(actual,D,have), guideline_arg(actual,D,1,A), guideline_arg(actual,D,2,B), guideline_pp(actual,D,during,C), guideline_entity(actual,E,clinician,countable), guideline_cardinality(actual,E,na,eq,1).
% S3: Every standard-buprenorphine-titration-interval should approximate 2 hours.
guideline_operator(actual,'$guideline_id'(context,'cdc2022-opioid-s59-06',3,box(1),[A]),should) :- guideline_entity(actual,A,'standard-buprenorphine-titration-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_entity('$guideline_id'(context,'cdc2022-opioid-s59-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-06',3,ref(2),[A]),hour,countable) :- guideline_entity(actual,A,'standard-buprenorphine-titration-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_cardinality('$guideline_id'(context,'cdc2022-opioid-s59-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-06',3,ref(2),[A]),na,eq,2) :- guideline_entity(actual,A,'standard-buprenorphine-titration-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_event('$guideline_id'(context,'cdc2022-opioid-s59-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-06',3,ref(3),[A]),approximate) :- guideline_entity(actual,A,'standard-buprenorphine-titration-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-06',3,ref(3),[A]),1,A) :- guideline_entity(actual,A,'standard-buprenorphine-titration-interval',countable), guideline_cardinality(actual,A,na,eq,1).
guideline_arg('$guideline_id'(context,'cdc2022-opioid-s59-06',3,box(1),[A]),'$guideline_id'(product,'cdc2022-opioid-s59-06',3,ref(3),[A]),2,'$guideline_id'(product,'cdc2022-opioid-s59-06',3,ref(2),[A])) :- guideline_entity(actual,A,'standard-buprenorphine-titration-interval',countable), guideline_cardinality(actual,A,na,eq,1).
